/**
 * Project TITAN — Blueprint Registry (V2.0 · Task 중심)
 */

export {
  TITAN_BLUEPRINTS_V17,
  TITAN_BLUEPRINTS_V20,
  getBlueprintV17,
  listBlueprintsV17,
  HOME_BLUEPRINT,
  EQUIPMENT_MONITOR_BLUEPRINT,
  OPERATIONS_MANAGEMENT_BLUEPRINT,
  PRODUCTION_MANAGEMENT_BLUEPRINT,
  QUALITY_MANAGEMENT_BLUEPRINT,
  STATISTICS_BLUEPRINT,
  MASTER_DATA_BLUEPRINT,
  ENVIRONMENT_BLUEPRINT,
  COMPANY_INFO_BLUEPRINT,
  LOT_LIFECYCLE_BLUEPRINT,
  MOBILE_QR_PORTAL_BLUEPRINT,
  QR_MENU_SHORTCUT_BLUEPRINT,
} from "./titanBlueprintsV17.js";

export { defineBlueprint } from "./blueprintSections.js";
export { MOBILE_QR_PORTAL_URL_POLICY } from "./mobileQrPortalBlueprint.js";
export { QR_MENU_SHORTCUT_ITEMS, QR_MENU_SHORTCUT_ROUTES } from "./qrMenuShortcutBlueprint.js";
export {
  TITAN_V101_EXPANSION_BLUEPRINT,
  TITAN_V101_EXPANSION_VERSION,
  TITAN_V101_EXPANSION_STATUS,
  TITAN_V101_QR_ENGINE_POLICY,
  TITAN_V101_MOBILE_QR_PORTAL_POLICY,
  TITAN_V101_WORK_TYPE_POLICY,
  TITAN_V101_SHOT_WORK_STATUS_BLUEPRINT,
  TITAN_V101_STATISTICS_EXPANSION_POLICY,
  TITAN_V101_KPI_UI_POLICY,
  TITAN_V101_INCOMING_DOCUMENT_ARCHIVE_POLICY,
  TITAN_V101_ACCOUNTING_LITE_POLICY,
  TITAN_V101_FOUNDATION_ATTACHMENT_GLOBAL_POLICY,
  TITAN_V101_FOUNDATION_REUSE_POLICY,
  TITAN_V101_APPROVED_IMPLEMENTATION_SEQUENCE,
  TITAN_V101_IMPLEMENTATION_PRINCIPLES,
  TITAN_V101_LONG_TERM_EXPANSION_PRINCIPLES,
  getTitanV101ExpansionSummary,
} from "./titanV101ExpansionBlueprint.js";

export {
  TITAN_V102_FOUNDATION_ACTION_TDE_POLICY,
  TITAN_V102_POLICY_VERSION,
  TITAN_V102_POLICY_STATUS,
  TITAN_V102_FOUNDATION_ACTION_BAR_POLICY,
  TITAN_V102_TDE_INTEGRATION_POLICY,
  TITAN_V102_IMPLEMENTATION_GATE,
  getTitanV102FoundationActionTdeSummary,
} from "./titanV102FoundationActionTdePolicy.js";

export {
  TITAN_V101_FOUNDATION_WORKSPACE_LAYOUT_POLICY,
  TITAN_V101_FOUNDATION_WORKSPACE_LAYOUT_VERSION,
  TITAN_V101_FOUNDATION_WORKSPACE_LAYOUT_STATUS,
  TITAN_FOUNDATION_WORKSPACE_LAYOUT_TYPES,
  TITAN_FOUNDATION_SEARCH_PANEL_POLICY,
  TITAN_FOUNDATION_ACTION_BAR_LAYOUT_POLICY,
  TITAN_ACCOUNTING_LITE_BUSINESS_LAYOUT_POLICY,
  TITAN_FOUNDATION_WORKSPACE_LAYOUT_GALLERY_POLICY,
  TITAN_FOUNDATION_WORKSPACE_LAYOUT_SELECTION_GUIDE,
  getTitanFoundationWorkspaceLayoutSummary,
} from "./titanV101FoundationWorkspaceLayout.js";
