/**
 * Project TITAN — Blueprint Registry (V2.0 · Task 중심)
 */

export {
  TITAN_BLUEPRINTS_V17,
  TITAN_BLUEPRINTS_V20,
  getBlueprintV17,
  listBlueprintsV17,
  HOME_BLUEPRINT,
  EQUIPMENT_MONITOR_BLUEPRINT,
  OPERATIONS_MANAGEMENT_BLUEPRINT,
  PRODUCTION_MANAGEMENT_BLUEPRINT,
  QUALITY_MANAGEMENT_BLUEPRINT,
  STATISTICS_BLUEPRINT,
  MASTER_DATA_BLUEPRINT,
  ENVIRONMENT_BLUEPRINT,
  COMPANY_INFO_BLUEPRINT,
  LOT_LIFECYCLE_BLUEPRINT,
} from "./titanBlueprintsV17.js";

export { defineBlueprint } from "./blueprintSections.js";
