/**
 * Project TITAN — Page Blueprints (V2.0 · Task 중심 · PM 최종 승인 2026-07-07)
 *
 * Architecture → Blueprint → PM 승인 → 구현 → QA → Freeze
 * V2.0 11-section: Purpose · Role · Task Scope · Exit Condition · Layout · Data · Workflow
 *   · Automation · Connected Screens · Output · Freeze Criteria
 *
 * 핵심: 페이지 = 업무 공간(Workspace) — 담당자가 '지금 처리할 업무'만 표시.
 *       동일 LOT를 여러 화면에서 반복 표시 ❌ · 완료 시 다음 화면 자동 이동.
 *
 * @see src/config/titanV20MenuWorkflowArchitecture.js
 * @see docs/blueprints/V2.0/INDEX.md
 */

import { defineBlueprint } from "./blueprintSections.js";
import { DOCUMENT_MANAGEMENT_V101_BLUEPRINT } from "./documentManagementV101Blueprint.js";
import { MOBILE_QR_PORTAL_BLUEPRINT } from "./mobileQrPortalBlueprint.js";
import { QR_MENU_SHORTCUT_BLUEPRINT } from "./qrMenuShortcutBlueprint.js";

/** @typedef {ReturnType<typeof defineBlueprint>} TitanBlueprint */

export const HOME_BLUEPRINT = defineBlueprint({
  id: "home",
  label: "HOME",
  order: 1,
  menuId: "home",
  route: "/home",
  docPath: "docs/blueprints/V2.0/home.md",
  status: "frozen",
  frozenDate: "2026-07-07",
  reviewStatus: "frozen",
  freezePolicy: "구조 변경 ❌ · 개선 필요 시 Review 문서(Update) 방식만",
  currentUiStatus: "ui-freeze-v15-as-built",
  workspaceFirst: {
    metaphor: "회사 전체 상황 — 통합 Dashboard (담당자 책상 ❌ · 상황판 ✅)",
    tenSecondGoal: ["오늘 무엇을 해야 하는지", "공장이 어떻게 돌아가는지", "문제가 있는지"],
  },
  purpose:
    "회사 전체를 한눈에 보는 통합 Dashboard. 금일·진행 요약 · Launcher. 업무 수행 ❌ — 현재 상황만 표시.",
  role: {
    allowed: [
      "회사 전체 운영현황 요약 조회 (10초 파악 목표)",
      "공지사항 · 업무일정 확인/등록",
      "최근 작업 Timeline 요약 → 이력조회",
      "카드·위젯 클릭 → 해당 Workspace Launcher 이동",
    ],
    forbidden: [
      "업무 수행 (입고등록 · 출고등록 · 검사등록 · 성적서 발행 등)",
      "LOT/입고/출고/검사 전체 리스트",
      "Master Data CRUD",
      "V2.0 Blueprint 승인 전 레이아웃 변경",
    ],
  },
  taskScope: {
    workspaceRole: "회사 전체 상황 — Workspace First Dashboard (작업 화면 ❌)",
    displayOnly: "요약 정보만 (건수·지표·요약) — 리스트 ❌",
    showOnly: [
      "오늘 입고",
      "오늘 출고",
      "생산 진행",
      "검사 대기",
      "성적서 미발행",
      "설비 가동률",
      "오늘 일정",
      "공지사항",
      "최근 알림",
      "실시간 진행현황",
    ],
    hide: [
      "전체 LOT 리스트",
      "전체 입고 리스트",
      "전체 출고 리스트",
      "전체 검사 리스트",
      "업무 수행 폼 · 상세 CRUD",
    ],
    pmReview: "⚠️ 보완 → ✅ 반영 (요약 10항목 확정 · 리스트 금지 명시)",
  },
  exitCondition: {
    completeWhen: "해당 없음 — HOME은 Workflow 종료 지점이 아님 (진입 Hub)",
    removeFromScreen: "해당 없음",
    nextScreen: "카드/위젯 클릭 → V2.0 Launcher → 해당 Workspace",
    engine: "Launcher 라우팅만 — Workflow stage 전환 ❌",
    launcherPolicy: {
      rule: "모든 KPI 카드·Widget = V2.0 Launcher 정책 준수 (Legacy Route ❌)",
      transitions: [
        { from: "오늘 입고", via: "운영관리", to: "입고등록" },
        { from: "검사 대기", via: "품질관리", to: "검사관리" },
        { from: "설비 가동률", via: "설비현황", to: "설비현황" },
      ],
    },
    legacyRoutes: {
      status: "Blueprint에 Legacy 표기 · 향후 제거 대상",
      examples: ["/inout/incoming", "/inout/shipment", "/quality/inspection", "/quality/certificate"],
      plan: "구현 단계에서 V2.0 Launcher Hub 경로로 교체 후 Legacy Route 제거",
    },
    pmReview: "⚠️ 보완 → ✅ 반영 (Launcher 정책 · Legacy 제거 계획 명시)",
  },
  layout: [
    "PageTopBar (HOME · 새로고침)",
    "HomeTodaySummary — 실시간 진행현황 요약 (클릭 → Workspace)",
    "좌: 공지 · 업무일정 · 최근작업 Timeline",
    "우: 업무 바로가기 Launcher (클릭 → Workspace)",
  ],
  data: {
    stores: ["dashboardStore", "lotStore", "equipmentStore"],
    session: ["homeNoticesSession", "homeTasksSession"],
    refresh: "subscribeWorkflowDataRefresh → refreshKey",
    legacy: {
      current: "getSessionProductionRecords() (Session 기반) — Legacy 명시",
      target: "TitanDataEngine · TitanWorkflowEngine 기반 전환",
      plan: [
        "records → TitanDataEngine 조회로 교체",
        "진행현황·KPI → TitanWorkflowEngine stage 집계",
        "UI/Layout 불변 · Data Source만 교체 (Repository 정책)",
      ],
    },
    gapItems: [
      "설비 가동률 KPI 상단 미표시 (Launcher metrics에만 부분 존재)",
      "오늘 입고/출고 — 상단 요약 미통합",
      "최근 알림 전용 Widget 없음 (Timeline으로 부분 대체)",
    ],
    pmReview: "⚠️ 보완 → ✅ 반영 (Session=Legacy · Engine 전환 계획 기록)",
  },
  workflow: [
    "Foundation Store 집계 → 요약 카드/Launcher metrics",
    "Workflow 이벤트 → refresh → 재계산",
    "카드·위젯 클릭 → V2.0 Launcher → Task Workspace 이동",
    "HOME 자체 Workflow stage 전환 ❌ (상태 변경 없음)",
  ],
  automation: {
    user: ["새로고침", "공지 등록", "업무일정"],
    system: ["KPI 집계", "공지", "일정", "최근 알림", "진행현황", "Workflow refresh"],
  },
  connectedScreens: [
    "운영관리(입고·출고)",
    "생산관리",
    "품질관리(검사·성적서)",
    "설비현황",
    "통계관리",
    "이력조회",
  ],
  connectedScreensPolicy: {
    note: "HOME에서 제품현황 직접 연결 ❌",
    deferred: "설비현황 · 제품현황 구조는 ② 설비현황 Blueprint Review에서 최종 확정",
    pmReview: "⚠️ 보완 → ✅ 반영 (제품현황 연결 ② 설비현황에서 확정)",
  },
  outputs: ["없음 (Dashboard)"],
  completionCriteria: [
    "Workspace Principle 충족 (작업 ❌ · 요약+Launcher ✅)",
    "Launcher 정책 충족 (Legacy Route 제거 계획 명시)",
    "Task Scope 정의 완료 (요약 10항목 · 리스트 금지)",
    "Exit Condition 정의 완료 (Launcher 전환)",
    "Legacy 전환 계획 정의 (Session → TitanDataEngine/WorkflowEngine)",
    "PM 승인 (Screen Review)",
  ],
  pmReviewResult: {
    method: "Screen Review (항목별 승인 ❌)",
    date: "2026-07-07",
    sections: {
      purpose: "approved",
      role: "approved",
      taskScope: "approved",
      exitCondition: "approved",
      layout: "approved",
      data: "approved",
      workflow: "approved",
      automation: "approved",
      connectedScreens: "approved",
      output: "approved",
      freeze: "approved-frozen",
    },
    finalReviewDate: "2026-07-07",
    frozen: true,
    supplementsApplied: [
      "Task Scope — 요약 정보만",
      "Exit Condition — Launcher 정책 · Legacy 제거 계획",
      "Data — TitanDataEngine/WorkflowEngine 전환 계획",
      "Connected — 제품현황 ② 설비현황에서 확정",
    ],
    nextStep: "Official Freeze — ② 설비현황 Blueprint Review",
  },
});

export const EQUIPMENT_MONITOR_BLUEPRINT = defineBlueprint({
  id: "equipmentMonitor",
  label: "설비현황",
  order: 2,
  menuId: "equipmentMonitor",
  launcher: false,
  routes: {
    controlRoom: "/equipment-status",
    legacy: ["/equipment-status", "/product-status"],
    note: "/product-status = Legacy · Control Room 내부 제품 View로 흡수 · Sidebar ❌",
  },
  docPath: "docs/blueprints/V2.0/equipment-monitor.md",
  status: "frozen",
  frozenDate: "2026-07-07",
  reviewStatus: "frozen",
  freezePolicy: "구조 변경 ❌ · 개선 = Review 문서(Update)만",
  isWorkspace: false,
  roleType: "realTimeMonitor",
  lotCentric: true,
  controlRoomStructure: {
    pmDecision: "조건부 승인 — LOT 중심 Control Room",
    tree: [
      "설비현황 (Control Room · Sidebar 1Depth)",
      "├ 설비 View",
      "├ LOT View (🆕 중심)",
      "└ 제품 View (LOT 구성 정보 · 독립 Workspace ❌)",
    ],
    sidebarPolicy: "제품현황 Sidebar 제거 ✅",
    navigation: "HOME → 설비현황 → Control Room → View 전환",
  },
  purpose:
    "LOT 중심 공장 실시간 관제(Control Room). 공장 현재 상태 모니터링 — 설비 중심 ❌ · LOT/Workflow 중심 ✅. Workspace ❌ · 작업 ❌.",
  role: {
    allowed: [
      "실시간 관제 조회 (설비 · LOT · 제품 View)",
      "Control Room 상단 KPI · View 전환",
      "병목·가동·알람 파악 (한눈에)",
    ],
    forbidden: ["등록 · 수정 · 삭제 · 작업", "QR·장입·완료", "Master 편집", "Workflow 수동 변경", "Task List"],
  },
  taskScope: {
    roleType: "실시간 관제 화면 (Workspace ❌)",
    displayOnly: "실시간 상태·지표 — Task List · CRUD ❌",
    topKpi: [
      "현재 가동 설비",
      "가동률",
      "생산중 LOT",
      "대기 LOT",
      "알람",
      "금일 생산완료",
      "금일 검사대기",
    ],
    views: {
      equipment: ["설비 상태", "작업자", "현재 LOT", "현재 제품", "작업 시작", "예상 종료", "설비 알람", "가동률"],
      lot: [
        "LOT",
        "관리번호",
        "제품",
        "고객사",
        "현재 설비",
        "현재 공정",
        "작업자",
        "진행률",
        "상태",
        "작업 시작",
        "예상 종료",
      ],
      product: ["LOT", "제품명", "품번", "고객사", "현재 설비", "현재 공정", "진행률", "작업 시작", "예상 완료"],
    },
    hide: ["Progress Table (Task)", "Search+CRUD", "생산일보형 업무 UI"],
  },
  exitCondition: {
    completeWhen: "해당 없음 — 관제 화면",
    nextScreen: "작업 필요 → 생산관리 → 설비장입현황",
    engine: "TitanDataEngine → TitanWorkflowEngine → Control Room refresh",
    navigationPolicy: {
      fromHome: "설비 가동률 → 설비현황 Control Room",
      toWork: "Control Room → 생산관리 → 설비장입현황",
    },
  },
  layout: {
    shell: "Control Room Shell — 상단 KPI Bar + View Tab (설비 | LOT | 제품)",
    equipmentView: "Summary Bar · 공정별 Cards · Detail Panel (As-Built 유지 + 알람·작업자)",
    lotView: "LOT 중심 실시간 Monitor Grid (🆕)",
    productView: "실시간 관제 Monitor (Task Table ❌ · Legacy HomeProductProgressTable 제거 대상)",
    asBuiltGap: [
      "LOT View 미구현",
      "제품 View = Search + Progress Table (Task형 — Blueprint와 불일치)",
      "제품 Sidebar 1Depth 잔존 (V2.0 제거 대상)",
      "상단 KPI 7항목 미구현",
    ],
  },
  data: {
    pipeline: "TitanDataEngine → TitanWorkflowEngine → Control Room",
    stores: ["equipmentStore", "lotStore", "productionStore", "dashboardStore"],
    lotCentric: "LOT = Control Room 데이터 축 · 제품 = LOT 구성 정보",
    compute: "computeEquipmentRunStatus (저장 ❌ · 항상 계산)",
    ssot: "equipmentWorkflowService + lotStore (목표)",
    legacy: {
      productView: "getSessionProductionRecords() — Legacy",
      routes: ["/product-status Sidebar 1Depth"],
      plan: "Engine 기반 실시간 집계 · UI = 관제 Monitor로 재정의 (구현 단계)",
    },
  },
  workflow: [
    "TitanWorkflowEngine 이벤트 → lotStore/equipmentStore 갱신",
    "notifyWorkflowDataRefresh → Control Room 리렌더",
    "LOT 중심 상태 표시 — stage 변경은 생산관리에서만",
  ],
  automation: {
    user: ["View 전환 (설비|LOT|제품)", "관제 항목 선택 (조회)"],
    system: ["KPI 7항목", "가동률", "알람", "LOT/설비/제품 실시간 refresh"],
  },
  connectedScreens: ["HOME", "생산관리(설비장입)", "기준정보(설비)", "LOT Lifecycle (⑩)"],
  outputs: ["없음 (관제 Monitor)"],
  completionCriteria: [
    "LOT 중심 Control Room · Workspace ❌ · 작업 ❌",
    "3 View (설비|LOT|제품) + KPI 7항목",
    "제품 View = 관제 (Task ❌)",
    "Sidebar 제품현황 제거",
    "Data Pipeline (Engine) 전환 계획",
    "PM Final Review · Freeze",
  ],
  pmReviewResult: {
    method: "Screen Review",
    date: "2026-07-07",
    finalReviewDate: "2026-07-07",
    decision: "approved-frozen",
    approved: [
      "LOT 중심 Control Room",
      "3 View (설비|LOT|제품)",
      "Sidebar 제품 제거",
      "KPI 7항목",
      "Data Pipeline",
      "Navigation",
    ],
    supplementsApplied: [
      "LOT View 추가 (중심 View)",
      "제품 View 관제화",
      "KPI 7항목",
      "LOT 중심 Data",
    ],
    frozen: true,
    nextStep: "Official Freeze — ③ 운영관리 Blueprint Review",
  },
  migrationNote: "MES 삭제 → LOT 중심 Control Room · 제품=LOT 구성정보",
});

export const OPERATIONS_MANAGEMENT_BLUEPRINT = defineBlueprint({
  id: "operationsManagement",
  label: "운영관리",
  order: 3,
  menuId: "operationsManagement",
  workspaceId: "operationsWorkspace",
  legacyMenuId: "inoutManagement",
  legacyNaming: {
    status: "Legacy — Blueprint 표기 · 향후 제거 대상",
    items: [
      { legacy: "inoutManagement", target: "operationsManagement / Operations Workspace" },
      { legacy: "inoutManagementLauncher.js", target: "operationsManagementLauncher (구현 단계)" },
      { legacy: "route /inout", note: "유지 가능 · Workspace 명칭만 통일" },
    ],
    plan: "Blueprint·Config·Launcher 명칭 Operations Workspace로 통일 후 Legacy 제거",
  },
  route: "/inout",
  docPath: "docs/blueprints/V2.0/operations-management.md",
  status: "frozen",
  frozenDate: "2026-07-07",
  reviewStatus: "frozen",
  freezePolicy: "구조 변경 ❌ · 개선 = Review 문서(Update)만",
  isWorkspace: true,
  workspaceMetaphor: "회사 운영 업무 Workspace — TITAN 첫 실무 Workspace (등록·업무 수행)",
  roleSeparation: {
    home: "보는 화면 (Dashboard)",
    equipmentMonitor: "관제 화면 (Control Room)",
    operationsManagement: "일하는 화면 (본 Workspace)",
  },
  launcher: "TitanLauncherHubPage · inoutManagementLauncher.js (Legacy)",
  launcherStructure: {
    label: "운영관리 — Operations Workspace (입출고관리 ❌)",
    approved: true,
    cards: ["입고등록", "출고등록", "입출고이력", "재고관리", "출력관리", "영업업무일지"],
  },
  purpose:
    "회사 운영 업무를 수행하는 Workspace. TITAN에서 실제 등록·업무가 시작되는 첫 실무 영역. CRUD ❌ · 업무 흐름 수행 ✅.",
  role: {
    allowed: [
      "입고등록 · 출고등록 · 재고관리 (Task Workspace)",
      "입출고이력 (History Workspace — 전체 이력 조회)",
      "출력관리 (Print Workspace — 출력 전용)",
      "영업업무일지 (사람별 Launcher)",
    ],
    forbidden: ["생산 장입", "검사/성적서", "설비 QR", "타 단계 데이터 혼합", "사용자 수동 Workflow 변경"],
  },
  taskScope: {
    workspaceRole: "운영 담당자 — 지금 처리할 업무만",
    principle: "각 화면 = 자신의 Workflow 단계 데이터만 (History·Print 예외)",
    stageFilterPolicy: {
      rule: "각 화면은 자신의 단계(Stage) 데이터만 표시 — TitanWorkflowEngine stageKey 기준",
      engine: "TitanWorkflowEngine",
      userManualFilter: false,
    },
    screens: [
      {
        screen: "입고등록",
        type: "taskWorkspace",
        stageFilter: "RECEIVED · 생산 미투입",
        showOnly: ["입고 완료 → 생산 미투입 제품"],
        hide: ["생산계획 투입 완료 · 검사/출고 단계"],
        autoRemove: "생산계획 투입 시 입고등록에서 자동 제거",
      },
      {
        screen: "출고등록",
        type: "taskWorkspace",
        stageFilter: "SHIP_WAIT",
        showOnly: ["출고 대기"],
        extraTab: "출고완료",
        hide: ["입고·생산·검사 단계"],
      },
      {
        screen: "재고관리",
        type: "taskWorkspace",
        stageFilter: "inventory-on-hand",
        showOnly: ["현재 재고"],
        hide: ["생산 중 · 출고 완료"],
      },
      {
        screen: "입출고이력",
        type: "historyWorkspace",
        note: "Task Workspace ❌ · History Workspace — 전체 이력 조회 예외",
        showOnly: ["입고 + 출고 전체 이력"],
      },
      {
        screen: "출력관리",
        type: "printWorkspace",
        note: "출력 전용 Workspace",
        showOnly: ["입고리스트 · 출고리스트 · 거래명세서"],
        sharedLayout: "operationsProductionPrint",
        sharedComponent: "운영·생산 공통 출력 Component",
      },
      {
        screen: "영업업무일지",
        type: "departmentJournal",
        launcher: "사람별 (예: 영업부 → 홍길동 · 김대리 · 이과장)",
        note: "부서 → 담당자 Launcher 구조 유지",
      },
    ],
  },
  exitCondition: {
    engine: "TitanWorkflowEngine",
    rule: "모든 업무 완료 시 Engine이 자동으로 다음 Workspace로 이동 — 사용자 수동 stage 변경 ❌",
    userManualStageChange: false,
    transitions: [
      {
        screen: "입고등록",
        completeWhen: "입고등록 완료 → 생산계획 투입",
        removeFrom: "입고등록",
        nextScreen: "생산관리 → 생산계획",
      },
      {
        screen: "출고등록",
        completeWhen: "출고 완료",
        removeFrom: "출고등록",
        nextScreen: "입출고이력 (+ 출고완료 탭)",
      },
      {
        screen: "재고관리",
        completeWhen: "재고 이동",
        action: "재고 자동 갱신 (Engine)",
        nextScreen: "재고관리 (갱신된 현재 재고)",
      },
    ],
  },
  layout: [
    "Breadcrumb → Launcher Hub (6 cards · 구조 승인)",
    "Task/History/Print Workspace — list-centered · TitanDataTable",
    "출력관리 = 생산관리 동일 Layout · Component · UX (operationsProductionPrint)",
    "영업업무일지 = 부서 → 담당자 Launcher",
  ],
  data: {
    pipeline: "TitanDataEngine → TitanWorkflowEngine → Operations Workspace",
    stores: ["lotStore", "productionStore"],
    master: ["customerStore", "productStore"],
    stageFilter: "TitanWorkflowEngine stageKey per screen",
    legacy: {
      menuId: "inoutManagement",
      launcher: "inoutManagementLauncher.js",
      session: ["inboundManagementStatus", "outboundManagementStatus", "Session records"],
      plan: "Operations Workspace 명칭 통일 · Engine 기반 stage 필터 · UI 불변",
    },
  },
  workflow: [
    "입고등록 → 관리번호(MES) → LOT → LOT QR",
    "생산계획 투입 → 입고등록 제거 (Engine)",
    "생산관리 → 품질관리 → 성적서 → 출고등록 표시",
    "출고 완료 → 입출고이력",
    "재고 이동 → 재고 자동 갱신",
  ],
  workflowChain: [
    "입고등록 → 생산관리 → 품질관리 → 출고등록 → 입출고이력",
  ],
  automation: {
    user: ["입고/출고 · 출력 선택 · 영업일지 · 재고 조회"],
    system: ["Stage Filter", "Workflow 자동 이동", "LOT QR", "Document No.", "재고 갱신", "Timeline"],
  },
  printManagement: {
    sharedWith: "생산관리 출력관리",
    sharedLayoutId: "operationsProductionPrint",
    rule: "동일 Layout · 동일 Component · 동일 UX · 공통 Component Blueprint 명시",
    outputsOnlyHere: ["입고리스트", "출고리스트", "거래명세서"],
  },
  connectedScreens: {
    chain: "입고등록 → 생산관리 → 품질관리 → 출고등록 → 입출고이력",
    also: ["HOME", "설비현황", "LOT Lifecycle"],
  },
  outputs: {
    location: "출력관리에서만 출력",
    items: [
      "입고리스트 (DOC-01)",
      "출고리스트",
      "거래명세서 (DOC-04)",
      "LOT 라벨 (Operation QR — 입고 Workflow)",
    ],
  },
  completionCriteria: [
    "Workspace Principle · Launcher 6 cards",
    "Stage Filter per screen",
    "Exit Condition · TitanWorkflowEngine",
    "출력관리 공통 Component",
    "Legacy → Operations Workspace 전환 계획",
    "PM Final Review · Freeze",
  ],
  pmReviewResult: {
    method: "Screen Review",
    date: "2026-07-07",
    finalReviewDate: "2026-07-07",
    decision: "approved-frozen",
    approved: [
      "Purpose",
      "Role",
      "Task Scope",
      "Exit Condition",
      "Layout",
      "Data",
      "Workflow",
      "Automation",
      "Connected",
      "Output",
      "Freeze",
      "Launcher 6",
      "Workspace 유형 분류",
    ],
    supplementsApplied: [
      "Stage Filter (stageKey per screen)",
      "Exit Condition (TitanWorkflowEngine)",
      "Legacy inoutManagement → Operations Workspace",
    ],
    frozen: true,
    nextStep: "Official Freeze — ④ 생산관리 Blueprint Review",
  },
  asBuiltGap: [
    "Legacy inoutManagement menuId/launcher 명칭",
    "Stage Filter — List 중심 잔존 (구현 단계)",
    "출력관리 공통 Component — Blueprint만 · 구현 검증 대기",
    "Exit Condition Engine 연동 — partial",
  ],
});

export const PRODUCTION_MANAGEMENT_BLUEPRINT = defineBlueprint({
  id: "productionManagement",
  label: "생산관리",
  order: 4,
  menuId: "productionManagement",
  workspaceId: "productionWorkspace",
  route: "/production",
  docPath: "docs/blueprints/V2.0/production-management.md",
  status: "frozen",
  frozenDate: "2026-07-07",
  reviewStatus: "frozen",
  freezePolicy: "구조 변경 ❌ · 개선 = Review 문서(Update)만",
  isWorkspace: true,
  lotCentric: true,
  lotCentricPrinciple: {
    official: "생산관리 = 설비 관리 ❌ · LOT Workflow 관리 ✅",
    summary: "TITAN 핵심 엔진 — LOT가 살아 움직이는 Workspace · 설비는 LOT 수행 수단",
    designCenter: "LOT",
    notEquipmentManagement: true,
  },
  workspaceMetaphor: "LOT 계획→장입→생산→완료 — TITAN Workflow 중심",
  launcherStructure: {
    approved: true,
    cards: ["생산계획", "설비장입현황", "생산일보", "생산실적관리", "출력관리"],
    workspaceTypes: {
      task: ["생산계획", "설비장입현황", "생산일보"],
      analytics: ["생산실적관리"],
      print: ["출력관리"],
    },
    lotWorkflowChain:
      "입고완료 → 생산계획 → LOT 생성 → 작업지시 → 설비장입 → 생산진행 → 생산완료 → 검사관리",
  },
  purpose:
    "LOT를 계획→장입→생산→완료까지 관리하는 Production Workspace. TITAN Workflow 중심 · LOT 생명주기 핵심.",
  launcher: "productionManagementLauncher.js",
  role: {
    allowed: [
      "생산계획 (Task — HT_WAIT · LOT 생성)",
      "설비장입현황 (Task — LOT↔설비 연결 · 장입)",
      "생산일보 (Task — HT_RUNNING · UI Freeze V1.3)",
      "생산실적관리 (Analytics — 조회 전용)",
      "출력관리 (Print — 운영과 동일 Component)",
    ],
    forbidden: ["검사/성적서 (품질)", "설비 QR 생성 (기준정보)", "LOT QR 생성 (운영)", "사용자 수동 stage 변경"],
  },
  taskScope: {
    lotCentricPrinciple: "설비 관리 ❌ · LOT Workflow 관리 ✅ — 모든 생산 화면 HT Stage 기준",
    htStageDefinitions: {
      HT_WAIT: {
        label: "열처리 대기",
        screens: ["생산계획"],
        meaning: "입고완료 · LOT 생성·작업지시·생산 시작 전",
      },
      HT_RUNNING: {
        label: "열처리 진행",
        screens: ["설비장입현황", "생산일보"],
        meaning: "장입·생산 진행 중 (장입=LOT↔설비 · 일보=생산 진행/완료)",
      },
      HT_COMPLETE: {
        label: "열처리 완료",
        screens: ["생산일보(완료)", "생산실적관리"],
        meaning: "생산 완료 → Engine → 품질관리(검사관리)",
        workflowKey: "INSPECTION_WAIT",
      },
      policy: "모든 생산 화면 = HT Stage 기준 동작 · TitanWorkflowEngine stageKey",
    },
    stageFilterPolicy: {
      rule: "각 화면 = 자신의 HT Stage LOT만 · 동일 LOT 다른 Workspace 반복 ❌",
      engine: "TitanWorkflowEngine",
      userManualStageChange: false,
    },
    screens: [
      {
        screen: "생산계획",
        type: "taskWorkspace",
        stageFilter: "HT_WAIT",
        showOnly: ["열처리 대기품"],
        flow: ["LOT 생성", "작업지시 출력 (DOC-01)", "생산 시작"],
        hide: ["HT_RUNNING · HT_COMPLETE · 검사/출고"],
      },
      {
        screen: "설비장입현황",
        type: "taskWorkspace",
        hubRoute: "/production/charging",
        importance: "생산관리 최중요 Workspace — LOT를 설비에 연결",
        principle: "설비 중심 ❌ · LOT↔설비 연결 ✅",
        showOnly: ["장입 대기", "장입중 LOT"],
        displays: ["LOT", "설비", "장입시간", "예정 종료", "작업자", "상태"],
        completeState: "장입 완료 → 생산일보",
      },
      {
        screen: "생산일보",
        type: "taskWorkspace",
        stageFilter: "HT_RUNNING",
        showOnly: ["생산 진행", "생산 완료"],
        exitOnComplete: "품질관리 → 검사관리 (Engine · 수동 변경 ❌)",
        uiFreeze: "V1.3 UI Freeze 유지",
      },
      {
        screen: "생산실적관리",
        type: "analyticsWorkspace",
        role: "조회 전용 — Task ❌",
        dimensions: ["설비별", "업체별", "품명별", "재질별", "LOT별"],
        lotProductivity: "LOT별 생산성 분석 — LOT 중심 시스템 필수",
        showOnly: ["생산 완료(HT_COMPLETE) 데이터"],
      },
      {
        screen: "출력관리",
        type: "printWorkspace",
        sharedLayout: "operationsProductionPrint",
        sharedComponent: "운영관리 100% 동일 Component · Layout · UX",
        outputs: ["작업지시서", "생산일보 DOC-02", "LOT 리스트"],
      },
    ],
  },
  exitCondition: {
    engine: "TitanWorkflowEngine",
    rule: "LOT Workflow 완료 시 Engine이 자동 다음 Workspace — 사용자 수동 stage 변경 ❌",
    officialChain: [
      "LOT 생성 완료 → 설비장입",
      "생산 시작 → 생산일보",
      "생산 완료 → 품질관리(검사관리)",
    ],
    lotWorkflowChain: [
      { step: "LOT 생성 완료", nextScreen: "설비장입현황" },
      { step: "장입 완료 · 생산 시작", nextScreen: "생산일보" },
      { step: "생산 완료", nextScreen: "품질관리 → 검사관리" },
    ],
  },
  layout: [
    "Breadcrumb → Launcher Hub (5 cards)",
    "설비장입 Hub: /production/charging — QR Scan · 설비 · LOT · Timeline",
    "생산일보: KPI · Search · Table · Detail (UI Freeze V1.3)",
    "생산실적: Analytics Dashboard",
    "출력관리 = operationsProductionPrint",
  ],
  data: {
    pipeline: "TitanDataEngine → TitanWorkflowEngine → Production Workspace",
    stores: ["lotStore", "equipmentStore", "productionStore", "timelineStore", "dashboardStore"],
    lotCentric: "LOT = 데이터 축 · equipmentStore = LOT 수행 설비 (부속)",
    htStages: ["HT_WAIT", "HT_RUNNING", "HT_COMPLETE"],
    engine: "startCharging · finishCharging · HT_WAIT → HT_RUNNING → INSPECTION_WAIT",
    legacy: {
      session: "Session 기반 production records — Blueprint Legacy only",
      plan: "TitanDataEngine/WorkflowEngine 전환 · UI 불변 · 구현 단계",
    },
  },
  workflow: [
    "입고완료 → 생산계획 (HT_WAIT)",
    "LOT 생성 → 작업지시 출력 → 생산 시작",
    "설비장입 (LOT↔설비) → 생산일보 (HT_RUNNING)",
    "생산 완료 (HT_COMPLETE) → 품질관리 검사관리 (Engine)",
  ],
  automation: {
    user: ["LOT 선택", "메모·특이사항", "출력 선택"],
    system: ["생산일보 초안", "Timeline", "설비 상태", "Workflow stage 자동 이동", "Document No."],
  },
  printManagement: {
    sharedWith: "운영관리 출력관리",
    sharedLayoutId: "operationsProductionPrint",
    rule: "동일 Component · Layout · UX",
  },
  connectedScreens: {
    role: "TITAN Workflow 중심",
    chain: "운영관리 → 생산관리 → 품질관리",
    also: ["설비현황 Control Room", "HOME", "LOT Lifecycle"],
  },
  outputs: {
    location: "출력관리",
    items: ["작업지시서 (DOC-01)", "생산일보 DOC-02 + Traceability QR", "LOT 리스트", "PDF · Excel"],
  },
  completionCriteria: [
    "LOT 중심 원칙 (설비 관리 ❌ · LOT Workflow ✅)",
    "HT Stage 정의 (HT_WAIT · HT_RUNNING · HT_COMPLETE)",
    "Stage Filter · Exit Condition · Workflow Engine",
    "Analytics LOT별 생산성",
    "Print 공통 Component",
    "PM Final Review · Freeze",
  ],
  pmReviewResult: {
    method: "Screen Review",
    date: "2026-07-07",
    finalReviewDate: "2026-07-07",
    decision: "approved-frozen",
    approved: [
      "Purpose",
      "Role",
      "Task Scope",
      "Exit Condition",
      "Layout",
      "Data",
      "Workflow",
      "Automation",
      "Connected Screens",
      "Output",
      "Freeze Criteria",
      "Launcher 5",
    ],
    supplementsApplied: [
      "LOT별 생산성 분석 (생산실적)",
      "HT_WAIT · HT_RUNNING · HT_COMPLETE 정의",
      "LOT Workflow 관리 원칙 (설비 관리 ❌)",
    ],
    frozen: true,
    nextStep: "Official Freeze — ⑤ 품질관리 Blueprint Review",
  },
  asBuiltGap: [
    "HT Stage 필터 — List 중심 잔존 (구현 단계)",
    "LOT Workflow Engine 자동 이동 — partial",
    "생산실적 LOT별 Analytics — Blueprint만",
    "Legacy Session → Engine 전환",
  ],
});

export const QUALITY_MANAGEMENT_BLUEPRINT = defineBlueprint({
  id: "qualityManagement",
  label: "품질관리",
  order: 5,
  menuId: "qualityManagement",
  workspaceId: "qualityWorkspace",
  route: "/quality",
  docPath: "docs/blueprints/V2.0/quality-management.md",
  status: "frozen",
  frozenDate: "2026-07-07",
  reviewStatus: "frozen",
  freezePolicy: "구조 변경 ❌ · 개선 = Review 문서(Update)만",
  isWorkspace: true,
  lotCentric: true,
  qualityValidationEngine: {
    official: "LOT Quality Validation Engine",
    summary: "생산의 연장 ❌ · LOT Lifecycle 품질 보증 ✅",
    chain: "LOT → 생산완료 → 품질검증 → 성적서 → 출고",
    siblingEngines: {
      operations: "업무 시작 Workspace",
      production: "LOT Engine (생산)",
      quality: "LOT Quality Validation Engine (검증·인증)",
    },
  },
  lotCentricPrinciple: {
    official: "품질관리 = 검사 화면 ❌ · LOT Lifecycle 품질 검증 ✅",
    summary: "LOT를 검증하고 인증하는 Engine — Type·Status·Result 분리",
    designCenter: "LOT",
    notInspectionCentric: true,
  },
  workspaceMetaphor: "LOT Quality Validation — 검증→성적서→출고",
  launcher: "qualityManagementLauncher.js",
  launcherStructure: {
    approved: true,
    cards: ["검사관리", "성적서관리", "불량이력관리", "문서관리", "품질업무일지"],
    workspaceTypes: {
      task: ["검사관리", "성적서관리"],
      history: ["불량이력관리"],
      document: ["문서관리"],
      journal: ["품질업무일지"],
    },
    lotWorkflowChain:
      "생산완료(HT_COMPLETE) → 검사관리 → 성적서관리 → 운영관리 출고등록",
  },
  purpose:
    "LOT Lifecycle 품질 검증 Workspace (LOT Quality Validation Engine). HT_COMPLETE LOT 검증 → 성적서 → 출고 · Type·Status·Result 분리.",
  role: {
    allowed: [
      "검사관리 (Task — HT_COMPLETE · 검사 대기/진행)",
      "성적서관리 (Task — 검사완료 · 성적서 미발행)",
      "불량이력관리 (History — 불량 이력 조회)",
      "문서관리 (Document — 품질 문서)",
      "품질업무일지 (Journal)",
    ],
    forbidden: [
      "입고/출고 등록 (운영)",
      "설비 장입 (생산)",
      "LOT/Master QR 생성",
      "사용자 Stage/Status 수동 변경",
      "생산 진행 제품 표시",
    ],
  },
  taskScope: {
    lotCentricPrinciple: "검사 화면 ❌ · LOT Quality Validation ✅",
    inspectionDimensions: {
      rule: "Type · Status · Result 완전 분리 · 독립 관리 · 조합 필터",
      inspectionType: {
        label: "검사 종류 (Type)",
        values: ["양산검사", "개발검사", "기타검사"],
        purpose: "Tab/필터 — LOT 업무 분류 · Status/Result와 독립",
      },
      inspectionStatus: {
        label: "검사 상태 (Status)",
        chain: ["검사 대기", "검사 진행", "검사 완료", "성적서 대기", "성적서 완료"],
        purpose: "Workflow 차원 — TitanWorkflowEngine · Result와 독립",
        workflowKeys: {
          INSPECTION_WAIT: "검사 대기",
          INSPECTION_IN_PROGRESS: "검사 진행",
          INSPECTION_DONE: "검사 완료",
          CERT_WAIT: "성적서 대기",
          CERT_DONE: "성적서 완료",
        },
      },
      inspectionResult: {
        label: "검사 판정 (Result)",
        values: ["PASS", "FAIL", "HOLD", "REWORK"],
        purpose: "품질 결과 — Status와 별개 · Workflow 상태 ≠ 품질 판정",
        examples: [
          "양산검사 + 검사 완료 + PASS",
          "개발검사 + 검사 완료 + HOLD",
          "기타검사 + 검사 완료 + FAIL → 불량이력",
          "REWORK → 재처리 → 재검사",
        ],
        policy: "Result는 Status 완료 시점에 기록 · FAIL/REWORK → 불량이력 분기",
      },
      typeStatusExamples: [
        "양산검사 + 검사 진행",
        "개발검사 + 검사 완료",
      ],
      typeStatusResultExamples: [
        "양산검사 + 검사 완료 + PASS",
        "개발검사 + 검사 완료 + HOLD",
      ],
      policy: "Type × Status × Result 조합 · Status/Result는 Engine·검사자 기록 · 사용자 Stage 수동 변경 ❌",
    },
    entryFromProduction: {
      productionStage: "HT_COMPLETE",
      qualityEntry: "검사관리 · 검사 대기 (INSPECTION_WAIT)",
      rule: "생산 완료 LOT만 · 생산 진행(HT_RUNNING) 제품 표시 ❌",
    },
    stageFilterPolicy: {
      rule: "각 화면 = 자신의 Status LOT만 · 동일 LOT 다른 Workspace 반복 ❌",
      engine: "TitanWorkflowEngine",
      userManualStageChange: false,
    },
    screens: [
      {
        screen: "검사관리",
        type: "taskWorkspace",
        entryRequirement: "HT_COMPLETE (생산 완료)",
        showOnly: ["검사 대기 · 검사 진행 LOT"],
        statusFilter: ["INSPECTION_WAIT", "INSPECTION_IN_PROGRESS"],
        typeFilter: ["양산검사", "개발검사", "기타검사"],
        resultOnComplete: ["PASS", "FAIL", "HOLD", "REWORK"],
        exitOnComplete: "검사 완료 (+ Result) → 성적서관리 (Engine · PASS/HOLD)",
        branchOnResult: { FAIL: "불량이력관리", REWORK: "재처리 → 재검사" },
        hide: ["생산 진행 · HT_RUNNING · HT_WAIT · 출고 단계"],
      },
      {
        screen: "성적서관리",
        type: "taskWorkspace",
        showOnly: ["검사 완료 · 성적서 미발행"],
        statusFilter: ["INSPECTION_DONE", "CERT_WAIT"],
        exitOnComplete: "성적서 발행 완료 → 운영관리 출고등록 (Engine)",
        hide: ["검사 대기/진행 · 생산 단계"],
      },
      {
        screen: "불량이력관리",
        type: "historyWorkspace",
        role: "불량 이력 조회 · FAIL/REWORK 분기",
        showOnly: ["불량 등록 LOT · FAIL · REWORK"],
        fields: ["불량 등록", "원인", "조치", "재발방지", "이력 조회"],
        branch: "FAIL → NCR → 재처리 → 재검사",
      },
      {
        screen: "문서관리",
        type: "documentWorkspace",
        showOnly: ["품질 문서"],
        categories: ["표준서", "공정서", "고객문서", "ISO", "도면"],
      },
      {
        screen: "품질업무일지",
        type: "journalWorkspace",
        role: "품질 담당자 업무일지",
      },
    ],
    hide: ["입고/생산/출고 단계 LOT (해당 Workspace 제외)"],
  },
  exitCondition: {
    engine: "TitanWorkflowEngine",
    rule: "LOT 품질 Workflow 완료 시 Engine이 자동 다음 Workspace — 사용자 수동 stage 변경 ❌",
    officialChain: [
      "검사 완료 → 성적서관리",
      "성적서 발행 완료 → 운영관리 출고등록",
    ],
    lotWorkflowChain: [
      { step: "검사 완료", nextScreen: "성적서관리", status: "성적서 대기" },
      { step: "성적서 발행 완료", nextScreen: "운영관리 → 출고등록", status: "출고 대기" },
    ],
  },
  layout: [
    "Breadcrumb",
    "Launcher Hub",
    "검사/성적서: Tab · KPI · Search · Table · Detail Popup",
  ],
  data: {
    pipeline: "TitanDataEngine → TitanWorkflowEngine → Quality Workspace",
    stores: ["qualityStore", "lotStore", "timelineStore"],
    lotCentric: "LOT = 데이터 축 · type/status/result = LOT 품질 속성 (분리)",
    inspectionResult: ["PASS", "FAIL", "HOLD", "REWORK"],
    statusKeys: [
      "INSPECTION_WAIT",
      "INSPECTION_IN_PROGRESS",
      "INSPECTION_DONE",
      "CERT_WAIT",
      "CERT_DONE",
    ],
    calc: ["heatTreatmentCalculationEngine"],
    legacy: {
      session: ["inspectionLogSession", "certificateSession", "qualityDocumentRegistry"],
      plan: "TitanDataEngine/WorkflowEngine 전환 · UI 불변 · 구현 단계",
    },
  },
  workflow: [
    "생산완료(HT_COMPLETE) → 검사관리 (검사 대기 · INSPECTION_WAIT)",
    "검사 진행 → 검사 완료 → 성적서관리 (성적서 대기)",
    "성적서 발행 완료 → 운영관리 출고등록 (Engine)",
    "불합격 → 불량이력 → NCR → 재처리 → 재검사",
  ],
  automation: {
    user: ["검사값", "판정", "성적서 승인", "경도 최종값"],
    system: ["유효경화깊이 계산", "Workflow 자동 이동", "Timeline", "Document No.", "Traceability QR"],
  },
  connectedScreens: {
    role: "LOT Lifecycle 품질 검증",
    from: "생산관리 (HT_COMPLETE · 생산 완료)",
    to: "운영관리 (출고등록)",
    also: ["LOT Lifecycle", "기준정보(제품 Spec)", "HOME"],
  },
  outputs: ["검사일지", "성적서 COA + Traceability QR", "PDF"],
  completionCriteria: [
    "LOT Quality Validation Engine 원칙",
    "Inspection Type · Status · Result 분리",
    "Stage/Status Filter · Exit Condition · Workflow Engine",
    "검사→성적서→출고 자동 이동",
    "History/Document/Journal Workspace 유형",
    "PM Final Review · Freeze",
  ],
  pmReviewResult: {
    method: "Screen Review",
    date: "2026-07-07",
    finalReviewDate: "2026-07-07",
    decision: "approved-frozen",
    approved: [
      "Purpose",
      "Role",
      "Task Scope",
      "Exit Condition",
      "Layout",
      "Data",
      "Workflow",
      "Automation",
      "Connected Screens",
      "Output",
      "Freeze Criteria",
      "Launcher 5",
      "Workspace Types",
      "Type/Status/Result 분리",
    ],
    supplementsApplied: [
      "LOT Quality Validation Engine",
      "Inspection Result (PASS/FAIL/HOLD/REWORK)",
      "불량이력 History Workspace",
      "검사관리 HT_COMPLETE · 생산진행 제외",
      "성적서관리 → 출고등록 Engine Exit",
    ],
    frozen: true,
    nextStep: "Official Freeze — ⑥ 통계관리 Blueprint Review",
  },
  asBuiltGap: [
    "Type/Status/Result 3축 필터 — Blueprint only",
    "INSPECTION_IN_PROGRESS · inspectionResult — 구현 단계",
    "Engine 자동 Exit — partial",
    "Legacy Session → Engine 전환",
  ],
});

export const STATISTICS_BLUEPRINT = defineBlueprint({
  id: "statistics",
  label: "통계관리",
  order: 6,
  menuId: "statisticsInquiry",
  workspaceId: "statisticsWorkspace",
  route: "/statistics",
  docPath: "docs/blueprints/V2.0/statistics.md",
  status: "frozen",
  frozenDate: "2026-07-07",
  reviewStatus: "frozen",
  freezePolicy: "구조 변경 ❌ · 개선 = Review 문서(Update)만",
  isWorkspace: true,
  isAnalyticsWorkspace: true,
  lotCentric: true,
  analyticsWorkspacePrinciple: {
    official: "업무 화면 ❌ · 경영 의사결정 지원 분석 화면 ✅",
    summary: "LOT Workflow를 분석하는 Analytics Engine — 등록/수정/삭제 ❌",
    role: "경영 현황 · 생산성 · 품질 · 영업 실적 분석 (조회 전용)",
  },
  readOnlyPolicy: {
    official: "Analytics = Read Only",
    rule: "통계는 절대 데이터를 수정하지 않는다 — 등록/수정/삭제 ❌",
    dataFlow: "TitanDataEngine → TitanWorkflowEngine → Timeline Store → Analytics (집계 조회)",
  },
  lotCentricPrinciple: {
    official: "설비별/업체별 통계 + LOT Traceability Analytics (핵심)",
    summary: "LOT 중심 분석 — 처리시간·공정·병목·불량률 + Lead Time·대기시간·REWORK",
    designCenter: "LOT",
  },
  launcher: "전체통계 · 생산통계 · 품질통계 · 영업통계",
  launcherStructure: {
    approved: true,
    cards: ["전체통계", "생산통계", "품질통계", "영업통계"],
    workspaceType: "analyticsWorkspace",
  },
  purpose:
    "경영 의사결정 지원 Analytics Workspace. LOT Workflow 분석 — 경영/생산성/품질/영업 + LOT Traceability. 조회 전용.",
  role: {
    allowed: [
      "기간·단위 조회",
      "KPI · Chart · List 분석",
      "Tab 전환 (전체/생산/품질/영업)",
      "LOT Traceability Analytics 조회",
    ],
    forbidden: ["등록/수정/삭제", "Workflow 상태 변경", "개별 업무 수행"],
  },
  taskScope: {
    workspaceRole: "경영·관리자 — 통계 분석 (조회 전용 · 업무 수행 ❌)",
    kpiPrinciple: {
      official: "상단 KPI = 사용자가 가장 먼저 보는 지표",
      items: [
        "금일 생산",
        "금일 출고",
        "금일 검사",
        "LOT 평균 리드타임",
        "불량률",
        "설비 가동률",
      ],
    },
    analyticsTabs: {
      전체통계: {
        role: "전체 회사 KPI",
        kpis: ["금일 입고", "금일 출고", "생산 완료", "검사 완료", "성적서 발행", "불량률", "설비 가동률"],
      },
      생산통계: {
        role: "생산성 분석",
        dimensions: ["설비별", "업체별", "품명별", "재질별", "LOT별"],
        note: "LOT별 필수",
      },
      품질통계: {
        role: "품질 분석",
        dimensions: ["PASS", "FAIL", "HOLD", "REWORK", "검사 종류", "LOT별 불량률"],
      },
      영업통계: {
        role: "영업 실적",
        dimensions: ["고객사별", "매출", "입고", "출고", "거래 건수", "납기 준수율"],
      },
    },
    lotTraceabilityAnalytics: {
      official: "PM 추가 · 강화 — LOT 중심 분석 (통계관리 핵심)",
      coreMetrics: [
        "LOT 처리 시간 (입고→출고 전체 리드타임)",
        "LOT 공정 소요 시간 (단계별 소요)",
        "LOT 병목 구간 (지연 단계 식별)",
        "LOT 불량률 (LOT 기준 불합격 비율)",
      ],
      enhancedMetrics: [
        "LOT 평균 Lead Time",
        "LOT 설비 대기시간",
        "LOT 검사 대기시간",
        "LOT 출고 대기시간",
        "LOT 재작업(REWORK) 횟수",
      ],
      purpose: "병목 분석 — 대기시간·REWORK 추적으로 원인 규명",
      note: "설비/업체 통계 + LOT Traceability — TITAN LOT 철학 핵심",
    },
    showOnly: ["집계·분석 데이터 (완료 단계 기반)"],
    hide: ["개별 업무 수행 폼"],
    removeOn: "해당 없음 (분석 전용)",
    nextScreen: "Drill Down 대상 Workspace 또는 종료",
  },
  exitCondition: {
    engine: "없음 — Analytics Workspace (Workflow 이동 ❌)",
    rule: "조회 종료 = Drill Down 또는 종료 · 상태 변경 없음",
    drillDown: {
      official: "PM 추가 — KPI 클릭 → 관련 Workspace/LOT Lifecycle 이동",
      principle: "통계는 숫자 표시 ❌ · 원인을 바로 확인 ✅",
      map: [
        { kpi: "불량률", target: "품질관리 → 불량이력관리" },
        { kpi: "설비 가동률", target: "설비현황" },
        { kpi: "LOT Lead Time", target: "LOT Lifecycle" },
        { kpi: "금일 생산", target: "생산관리" },
        { kpi: "금일 출고", target: "운영관리 → 출고" },
        { kpi: "금일 검사", target: "품질관리 → 검사관리" },
      ],
    },
  },
  layout: [
    "Breadcrumb",
    "KPI Bar (금일 생산·출고·검사 · LOT 평균 리드타임 · 불량률 · 설비 가동률 · Drill Down)",
    "조회 기준 (단위 · 기간 · 기준일)",
    "Dashboard Charts",
    "LOT Traceability Analytics (Core + Enhanced)",
    "Statistics List (접힘 기본)",
  ],
  data: {
    pipeline: "TitanDataEngine · TitanWorkflowEngine 집계 → buildExecutiveStatisticsDashboard() 단일 진입",
    stores: ["productionStore", "qualityStore", "lotStore", "timelineStore (LOT 소요·대기)"],
    lotCentric: "LOT Timeline = Traceability Analytics 축 (대기시간·Lead Time·REWORK)",
    readOnly: "Analytics = Read Only — 등록/수정/삭제 ❌",
    config: "statisticsExecutiveDashboard.js",
    legacy: {
      session: "Session 집계 — Blueprint Legacy only",
      plan: "TitanDataEngine/WorkflowEngine 집계 전환 · UI 불변",
    },
  },
  workflow: [
    "period/unitFilter/tab → 단일 analytics → KPI+Chart+List 동시 갱신",
    "LOT Traceability → Timeline 기반 리드타임·대기시간·병목·REWORK 분석",
    "KPI 클릭 → Drill Down → 관련 Workspace",
  ],
  automation: {
    user: ["기간", "Tab", "단위 필터", "KPI Drill Down 클릭"],
    system: ["KPI", "Chart series", "List rows", "LOT Traceability metrics", "Drill Down navigation"],
  },
  connectedScreens: {
    role: "LOT Workflow 분석 (경영 의사결정 지원)",
    from: ["운영관리", "생산관리", "품질관리 (완료 데이터 집계)"],
    drillDownTo: ["품질관리(불량이력)", "설비현황", "LOT Lifecycle", "생산관리", "운영관리"],
    also: ["HOME"],
  },
  outputs: ["Excel/PDF export (future)", "조회 전용"],
  completionCriteria: [
    "Analytics Workspace 원칙 (업무 화면 ❌)",
    "LOT Traceability Analytics (Core + Enhanced)",
    "Read Only (등록/수정/삭제 ❌)",
    "Dashboard KPI",
    "Drill Down (KPI → Workspace)",
    "Workflow Analytics · Single pipeline",
    "PM Final Review · Freeze",
  ],
  pmReviewResult: {
    method: "Screen Review",
    date: "2026-07-07",
    finalReviewDate: "2026-07-07",
    decision: "approved-frozen",
    approved: [
      "Purpose",
      "Role",
      "Task Scope",
      "Exit Condition (Drill Down/종료)",
      "Layout",
      "Data",
      "Workflow",
      "Automation",
      "Connected Screens",
      "Output",
      "Freeze Criteria",
      "Launcher 4",
    ],
    supplementsApplied: [
      "Read Only 정책 명시",
      "Dashboard Drill Down (KPI → Workspace)",
      "LOT Analytics 강화 (Lead Time·설비/검사/출고 대기·REWORK)",
    ],
    frozen: true,
    nextStep: "Official Freeze — ⑦ 기준정보관리 Blueprint Review",
  },
  asBuiltGap: [
    "LOT Traceability Analytics (Core+Enhanced) — Blueprint only",
    "Dashboard Drill Down — 구현 단계",
    "Timeline 기반 대기시간·병목 — 구현 단계",
    "Legacy Session → Engine 집계 전환",
  ],
});

export const MASTER_DATA_BLUEPRINT = defineBlueprint({
  id: "masterData",
  label: "기준정보관리",
  order: 7,
  menuId: "masterData",
  workspaceId: "masterDataWorkspace",
  route: "/settings",
  docPath: "docs/blueprints/V2.0/master-data.md",
  status: "frozen",
  frozenDate: "2026-07-07",
  reviewStatus: "frozen",
  freezePolicy: "구조 변경 ❌ · 개선 = Review 문서(Update)만",
  isWorkspace: true,
  masterDataWorkspacePrinciple: {
    official: "Master Data Workspace — 모든 Workspace가 참조하는 Master 단일 관리 영역",
    summary: "생산·품질 업무 수행 ❌ · Master SSoT 관리 ✅",
    referencedBy: ["운영관리", "생산관리", "품질관리", "통계관리", "LOT Lifecycle"],
    readWriteRule: "Master Store = 읽기/쓰기 가능한 유일한 공간 · 타 Workspace = Read Only",
  },
  masterStorePrinciple: {
    official: "각 Master = 단일 진실 공급원(SSoT) · 중복 관리 ❌",
    stores: [
      { store: "Customer Store", manages: "거래처" },
      { store: "Product Store", manages: "제품·품번·열처리 Spec·도면·Revision" },
      { store: "Material Store", manages: "재질" },
      { store: "Process Store", manages: "공정" },
      { store: "Equipment Store", manages: "설비·Equipment QR" },
      { store: "Worker Store", manages: "작업자 (Master Data)" },
      { store: "Company Store", manages: "회사정보 (회사정보 화면 관리)" },
    ],
    singleSourceExamples: [
      "제품명 수정 → Product Store만 변경 → 모든 화면 자동 반영",
      "설비명 수정 → Equipment Store만 변경",
      "작업자 정보 수정 → Worker Store만 변경",
    ],
    rule: "다른 Workspace는 참조만 · Master 수정은 해당 Store에서만",
  },
  // PM Screen Review 보완 ① — Master Version (변경 이력 버전 · Blueprint only)
  masterVersion: {
    official: "각 Master = 변경 버전 관리 (v1 → v2 → v3 …)",
    example: "Product Master v1 → v2 → v3",
    usage: "향후 변경 이력 관리 · 성적서/문서 Revision 연동",
    implementation: "Blueprint 정의만 · 구현 나중",
  },
  // PM Screen Review 보완 ② — Master Audit (변경 이력 · Blueprint only)
  masterAudit: {
    official: "모든 Master 변경 이력 기록",
    fields: ["수정자", "수정일", "변경 내용"],
    implementation: "Blueprint 정의만 · 구현 나중",
  },
  // PM Screen Review 보완 ③ — Equipment QR (설비관리)
  equipmentQr: {
    official: "설비관리 = Equipment QR 생성 포함",
    flow: "설비등록 → Equipment QR 생성 → Control Room → 생산관리",
    note: "설비당 1 QR · Master QR payload · Smart Access ID",
  },
  // PM Screen Review 보완 ④ — Product Master 확장 (제품관리)
  productMaster: {
    official: "제품관리 = 단순 품번 관리 ❌ · 확장 항목 공식화",
    fields: ["품번", "품명", "고객사", "재질", "열처리 Spec", "도면번호", "Revision"],
    usage: "향후 성적서 자동 생성 시 이 정보 그대로 사용",
  },
  // PM Screen Review 보완 ⑤ — Worker = Master Data
  workerMaster: {
    official: "작업자 = Master Data",
    referencedBy: ["생산일보", "검사관리", "LOT 로그", "권한(권한 관리)"],
  },
  launcher: "거래처 · 제품 · 재질 · 공정 · 설비 · 작업자",
  launcherStructure: {
    approved: true,
    cards: ["거래처관리", "제품관리", "재질관리", "공정관리", "설비관리", "작업자관리"],
  },
  purpose:
    "Master Data Workspace (SSoT). 모든 Workspace가 참조하는 Master 단일 관리 영역. Master First 정책 기준 · 설비 QR(Master) 생성.",
  role: {
    allowed: [
      "Master CRUD (Popup) — 유일한 읽기/쓰기 공간",
      "Equipment QR 생성·재생성·PDF (설비관리)",
      "제품 확장 항목 (품번·품명·고객사·재질·열처리 Spec·도면번호·Revision)",
      "Master Version · Audit (Blueprint 정의 · 구현 나중)",
      "삭제 가드 (in-use → soft delete)",
    ],
    forbidden: ["LOT/생산 Workflow 실행", "입고/출고 트랜잭션", "다른 Workspace의 Master 중복 관리"],
  },
  taskScope: {
    workspaceRole: "기준정보 담당자 — Master 등록·관리 (Master First)",
    showOnly: ["거래처 · 제품 · 재질 · 공정 · 설비 · 작업자"],
    hide: ["Workflow LOT 진행 데이터"],
    masterStoreSSoT: "각 Master = SSoT · 중복 관리 ❌ · 타 Workspace Read Only",
  },
  exitCondition: {
    completeWhen: "해당 없음 (Master 상시 유지)",
    removeFromScreen: "해당 없음",
    nextScreen: "전 화면 Master 참조 (Master First)",
    engine: "해당 없음",
  },
  layout: ["Breadcrumb", "Launcher Hub (6카드)", "List (TitanDataTable) → Detail Popup (Tabs)"],
  data: {
    stores: [
      "customerStore",
      "productStore",
      "materialStore",
      "processStore",
      "equipmentStore",
      "workerStore",
    ],
    companyStoreNote: "Company Store = 회사정보 화면 관리 (Master SSoT의 일부 · 별도 화면)",
    ssot: "각 Store = 단일 진실 공급원 · 중복 관리 ❌",
    readWritePolicy: {
      official: "Master Store = 읽기/쓰기 가능한 유일한 공간",
      otherWorkspaces: "Read Only (Master Store → Workspace 단방향 참조)",
    },
    version: "Master Version (v1→v2→v3) — Blueprint only",
    audit: "Master Audit (수정자·수정일·변경 내용) — Blueprint only",
    sync: "masterDataSync.js · initMasterDataStoresFromSessionStorage",
    note: "작업자관리 = workerStore (V2.0 Final · 회사정보에서 이동)",
  },
  workflow: [
    "Master 등록 → Store SSOT → 운영/생산/품질/통계/LOT Lifecycle에서 참조 (Read Only)",
    "Master 수정 → 해당 Store만 변경 → 모든 화면 자동 반영 (중복 관리 ❌)",
    "설비등록 → Equipment QR 생성 → Control Room → 생산관리",
  ],
  automation: {
    user: ["Master 필드 입력", "Equipment QR 생성 요청"],
    system: [
      "EquipmentStore seed",
      "Equipment QR / Smart Access ID",
      "삭제 가드",
      "Master Version 증가 (Roadmap)",
      "Master Audit 기록 (Roadmap)",
    ],
  },
  connectedScreens: {
    role: "Master SSoT — 전 Workspace 참조 (Read Only)",
    referencedBy: ["운영관리", "생산관리", "품질관리", "통계관리", "설비현황", "LOT Lifecycle"],
    workerReferencedBy: ["생산일보", "검사관리", "LOT 로그", "권한"],
    companyStore: "회사정보 (Company Store · 별도 화면)",
  },
  outputs: ["Equipment QR PDF (설비관리)"],
  completionCriteria: [
    "Master Store (7 Store · SSoT)",
    "SSoT · 타 Workspace Read Only",
    "Master Audit (Blueprint 정의)",
    "Master Version (Blueprint 정의)",
    "Equipment QR (설비관리)",
    "Worker Master",
    "PM Final Review · Freeze",
  ],
  pmReviewResult: {
    method: "Screen Review",
    date: "2026-07-07",
    finalReviewDate: "2026-07-07",
    decision: "approved-frozen",
    approved: [
      "Purpose",
      "Role",
      "Task Scope",
      "Exit Condition",
      "Layout",
      "Data",
      "Workflow",
      "Automation",
      "Connected Screens",
      "Output",
      "Freeze Criteria",
    ],
    supplementsApplied: [
      "Master Version (v1→v2→v3 · Blueprint only)",
      "Master Audit (수정자·수정일·변경 내용 · Blueprint only)",
      "Equipment QR (설비등록 → QR → Control Room → 생산)",
      "Product Master 확장 (품번·품명·고객사·재질·열처리 Spec·도면번호·Revision)",
      "Worker = Master Data",
      "Data 정책 (Master Store 유일한 R/W · 타 Workspace Read Only)",
    ],
    frozen: true,
    nextStep: "Official Freeze — ⑧ 환경설정 Blueprint Review",
  },
  asBuiltGap: [
    "Master Store 통합 (materialStore 등) — 구현 단계",
    "Master Version / Audit — Blueprint only · 구현 나중",
    "Company Store 분리 — 구현 단계",
    "Legacy Session → Engine 전환",
  ],
});

export const ENVIRONMENT_BLUEPRINT = defineBlueprint({
  id: "environment",
  label: "환경설정",
  order: 8,
  menuId: "environment",
  workspaceId: "systemAdminWorkspace",
  route: "/environment",
  docPath: "docs/blueprints/V2.0/environment.md",
  status: "frozen",
  frozenDate: "2026-07-07",
  reviewStatus: "frozen",
  freezePolicy: "구조 변경 ❌ · 개선 = Review 문서(Update)만",
  isWorkspace: true,
  systemAdminWorkspacePrinciple: {
    official: "System Administration Workspace — 시스템 동작 방식 관리",
    summary: "운영/생산/품질 데이터 직접 수정 ❌ · 설정으로 시스템 전체 동작 제어",
    scope: "설정 변경 → 시스템 전역 동작 반영",
  },
  launcher: "관리자 · 시스템 · 개발자 · QR등록",
  launcherStructure: {
    approved: true,
    cards: ["관리자", "시스템", "개발자", "QR 등록"],
  },
  // PM 추가 지시 — 3 Profile 기준 설계
  systemProfile: {
    official: "System Profile — 회사 기본 설정 · 시스템 옵션 · 출력 옵션 · QR 옵션",
    items: ["회사 기본 설정", "시스템 옵션", "출력 옵션", "QR 옵션"],
    note: "향후 Form Engine 연동",
  },
  permissionProfile: {
    official: "Permission Profile — 권한 프로파일 (Role 기반)",
    items: ["관리자", "일반 사용자", "읽기 권한", "쓰기 권한"],
  },
  environmentProfile: {
    official: "Environment Profile — 실행 환경",
    items: ["Development", "Test", "Production"],
  },
  // PM Screen Review 보완 ① — Role Profile (역할 기반 권한 · Blueprint only)
  roleProfile: {
    official: "권한 = Role 기반 관리",
    roles: ["Administrator", "Quality", "Production", "Sales", "Viewer"],
    implementation: "Blueprint 정의만 · 구현 나중",
  },
  // PM Screen Review 보완 ② — Feature Toggle (기능 On/Off 정책)
  featureToggle: {
    official: "Feature Toggle — 기능 확장 정책",
    items: ["Module ON/OFF (회계·영업 등)", "Print ON/OFF", "Workflow ON/OFF"],
  },
  // PM Screen Review 보완 ③ — QR Policy (QR 발급 정책)
  qrPolicy: {
    official: "QR 등록 = QR 발급 정책 관리 (생성 정책만 · 실제 생성은 Workflow)",
    types: ["Master QR", "LOT QR", "Traceability QR"],
    rule: "정책만 관리 · 실제 QR 생성은 Workflow에서 수행",
  },
  // System Policy — 시스템 전역 정책
  systemPolicy: {
    official: "System Policy — 시스템 전역 정책",
    items: ["Feature Toggle", "Module Enable/Disable", "Print Policy", "Workflow Policy"],
    examples: ["회계 모듈 On/Off", "영업 모듈 On/Off", "출력 정책", "Workflow 정책"],
  },
  purpose:
    "System Administration Workspace — 시스템 동작 방식 관리 (System/Permission/Environment Profile). 관리자·시스템·개발자·QR등록 설정. 저장경로 · MES PoC(Admin) · About.",
  role: {
    allowed: [
      "System Profile (회사 기본·시스템·출력·QR 옵션)",
      "Permission Profile (관리자·일반·읽기/쓰기 권한)",
      "Environment Profile (개발·테스트·운영)",
      "개발자 도구",
      "QR 등록 센터",
    ],
    forbidden: ["운영/생산/품질 데이터 직접 수정", "일상 생산/품질 업무", "Master Data 대체"],
  },
  taskScope: {
    workspaceRole: "시스템 관리자 — 설정으로 시스템 전체 제어",
    showOnly: ["System Profile", "Permission Profile", "Environment Profile", "개발자", "QR등록"],
    hide: ["업무 LOT 데이터", "운영/생산/품질 트랜잭션"],
    removeOn: "해당 없음",
    nextScreen: "해당 없음 (설정 반영은 전역)",
  },
  exitCondition: {
    completeWhen: "해당 없음 (설정 상시)",
    removeFromScreen: "해당 없음",
    nextScreen: "설정 변경 → 시스템 전역 반영",
    engine: "해당 없음",
  },
  layout: ["Breadcrumb", "Launcher Hub (4카드)", "Section panels per Profile"],
  data: {
    stores: ["dashboardStore (cache)"],
    config: ["operationMode", "titanEditionSession", "demoAdminPolicy"],
    profiles: {
      systemProfile: "회사 기본·시스템·출력·QR 옵션",
      permissionProfile: "관리자·일반·읽기/쓰기 권한 (Role 기반)",
      environmentProfile: "Development·Test·Production",
    },
    roleProfile: ["Administrator", "Quality", "Production", "Sales", "Viewer"],
    featureToggle: ["Module ON/OFF", "Print ON/OFF", "Workflow ON/OFF"],
    qrPolicy: ["Master QR", "LOT QR", "Traceability QR"],
    dataPolicy: {
      official: "System Setting → Engine → Workspace",
      rule: "설정만 변경 · 실제 업무 데이터 변경 ❌",
    },
    note: "설정만 관리 · 업무 데이터 직접 수정 ❌",
  },
  workflow: [
    "설정 변경 → Session/config persist → Sidebar/HOME 반영 (module)",
    "Role Profile → 사용자 역할 · 화면 접근 제어",
    "Feature Toggle → Module/Print/Workflow On·Off",
    "Environment Profile → Development/Test/Production 동작 전환",
    "QR Policy → 발급 정책 정의 (실제 생성은 Workflow)",
  ],
  automation: {
    user: ["설정값 입력", "Profile 선택", "Feature Toggle", "Edition (architecture)"],
    system: ["Demo Admin watermark", "Repository status display", "Role 기반 권한 게이트"],
  },
  connectedScreens: {
    role: "System Admin — 전역 설정 반영",
    referencedBy: ["전역", "기준정보(QR)", "HOME", "권한 게이트 전 화면", "Module 연동 화면"],
  },
  outputs: ["QR 출력센터 (Roadmap)"],
  completionCriteria: [
    "System Administration",
    "System Profile",
    "Permission Profile",
    "Role Profile",
    "Environment Profile",
    "QR Policy",
    "Feature Toggle",
    "PM Final Review · Freeze",
  ],
  pmReviewResult: {
    method: "Screen Review",
    date: "2026-07-07",
    finalReviewDate: "2026-07-07",
    decision: "approved-frozen",
    approved: [
      "Purpose",
      "Role",
      "Task Scope",
      "Exit Condition",
      "Layout",
      "Data",
      "Workflow",
      "Automation",
      "Connected Screens",
      "Output",
      "Freeze Criteria",
    ],
    supplementsApplied: [
      "Role Profile (Administrator·Quality·Production·Sales·Viewer)",
      "Feature Toggle (Module·Print·Workflow ON/OFF)",
      "QR Policy (Master·LOT·Traceability QR)",
      "System Policy (Feature Toggle·Module·Print·Workflow)",
    ],
    frozen: true,
    nextStep: "Official Freeze — ⑨ 회사정보 Blueprint Review",
  },
  asBuiltGap: [
    "Role Profile (역할 기반 권한) — Blueprint only · 구현 나중",
    "Feature Toggle (Module/Print/Workflow) — 구현 단계",
    "Environment Profile (Dev/Test/Prod) — 구현 단계",
    "QR 출력센터 — Roadmap",
  ],
});

export const COMPANY_INFO_BLUEPRINT = defineBlueprint({
  id: "companyInfo",
  label: "회사정보",
  order: 9,
  menuId: "companyInfo",
  workspaceId: "companyMasterWorkspace",
  route: "/company",
  docPath: "docs/blueprints/V2.0/company-info.md",
  status: "frozen",
  frozenDate: "2026-07-07",
  reviewStatus: "frozen",
  freezePolicy: "구조 변경 ❌ · 개선 = Review 문서(Update)만",
  isNew: true,
  isWorkspace: true,
  companyMasterWorkspacePrinciple: {
    official: "Company Master Workspace — 출력물·시스템 공통 회사 정보 단일 Master",
    summary: "Company Store SSoT · Form Engine 연동 · 모든 출력물은 참조만",
    referencedByOutputs: [
      "성적서",
      "검사리포트",
      "거래명세서",
      "작업지시서",
      "생산일보",
      "입출고리스트",
    ],
  },
  launcher: "회사 기본정보 · CI/Logo · 사업장 · 인증",
  launcherStructure: {
    approved: true,
    cards: ["회사 기본정보", "CI / Logo 관리", "사업장 정보", "인증 정보"],
  },
  // PM 추가 지시 — Company Master 3 블록
  companyMaster: {
    official: "Company Master — 회사 기본 정보",
    fields: ["회사명", "대표자", "사업자등록번호", "주소", "연락처", "이메일", "홈페이지"],
  },
  branding: {
    official: "Branding — CI · Logo · 직인 · 전자 서명",
    items: ["CI", "Logo", "직인", "전자 서명"],
  },
  // PM Screen Review 보완 ① — Brand Theme (출력물 품질 · Blueprint only)
  brandTheme: {
    official: "Brand Theme — 출력물 테마 (Form Engine 연동)",
    items: ["Primary Color", "Secondary Color", "Font", "Report Theme"],
    implementation: "Blueprint 정의만 · 구현 나중",
  },
  certification: {
    official: "Certification — 인증 정보 (유효기간·상태 포함)",
    items: ["ISO", "고객 인증", "기타 인증"],
    // PM Screen Review 보완 ② — Certification 확장
    fields: ["인증명", "인증번호", "발급기관", "유효기간", "상태"],
    roadmap: "인증 만료 알림 연계 (Blueprint 정의)",
  },
  // PM Screen Review 보완 ③ — Business Location (다중 사업장)
  businessLocation: {
    official: "Business Location — 사업장 정보 (다중 지원)",
    types: ["본사", "공장", "창고"],
    fields: ["사업장명", "주소", "연락처"],
    note: "향후 여러 사업장 지원 설계",
  },
  purpose:
    "Company Master Workspace (V2.0). Company Store SSoT — 회사 기본정보·Branding·Certification. 모든 출력물 Header/인증 공통 참조. 작업자관리 ❌ (기준정보관리).",
  role: {
    allowed: [
      "회사 기본정보 관리 (Company Master)",
      "Branding 관리 (CI·Logo·직인·서명)",
      "Certification 관리 (ISO·고객·기타 인증)",
    ],
    forbidden: ["작업자관리 (→ 기준정보관리)", "LOT/Workflow 실행", "Config/SessionStorage 저장"],
  },
  taskScope: {
    workspaceRole: "관리 담당자 — 회사 Master (출력물 공통)",
    showOnly: ["회사 기본정보", "CI/Logo/직인/서명", "사업장 정보", "인증 정보"],
    hide: ["업무 LOT 데이터", "작업자 명단"],
  },
  exitCondition: {
    completeWhen: "해당 없음 (회사정보 상시)",
    removeFromScreen: "해당 없음",
    nextScreen: "모든 출력물 Header/인증 자동 참조 (Read Only)",
    engine: "해당 없음",
  },
  layout: ["Breadcrumb", "Launcher Hub (4카드)", "회사정보 Form/Panel per block"],
  data: {
    stores: ["companyStore (신규 · Blueprint-only · SSoT)"],
    forbidden: ["config", "sessionStorage"],
    companyMaster: ["회사명", "대표자", "사업자등록번호", "주소", "연락처", "이메일", "홈페이지"],
    branding: ["CI", "Logo", "직인", "전자 서명"],
    brandTheme: ["Primary Color", "Secondary Color", "Font", "Report Theme"],
    certification: ["인증명", "인증번호", "발급기관", "유효기간", "상태"],
    businessLocation: {
      types: ["본사", "공장", "창고"],
      fields: ["사업장명", "주소", "연락처"],
    },
    readWritePolicy: "Company Store = 유일한 R/W · 출력물은 참조만 (Read Only)",
  },
  workflow: [
    "회사정보 등록/수정 → Company Store(SSoT) → Form Engine → 모든 출력물 반영",
    "Branding(직인·서명)·Brand Theme → 출력물 테마/서명 자동 적용",
    "Certification(유효기간·상태) → 만료 알림 연계 (Roadmap)",
  ],
  automation: {
    user: ["회사 Master 입력", "CI/Logo/직인/서명 업로드", "Brand Theme 설정", "인증 등록", "사업장 등록"],
    system: [
      "출력물(성적서·검사리포트·거래명세서·작업지시서·생산일보·입출고리스트) Header 자동 반영",
      "인증 만료 알림 (Roadmap)",
    ],
  },
  connectedScreens: {
    role: "Company Master — 전 출력물 공통 참조 (Read Only)",
    referencedByOutputs: [
      "성적서",
      "검사리포트",
      "거래명세서",
      "작업지시서",
      "생산일보",
      "입출고리스트",
    ],
    connected: ["환경설정(System Profile)", "Form Engine"],
  },
  outputs: ["회사정보 = 모든 출력물 공통 Header/Branding/인증"],
  completionCriteria: [
    "Company Master (기본정보)",
    "Branding (CI·Logo·직인·서명)",
    "Brand Theme (Color·Font·Report Theme)",
    "Business Location (본사·공장·창고)",
    "Certification (유효기간·상태 확장)",
    "Company Store SSoT (Config/Session ❌)",
    "출력물 Header 자동 참조 (Read Only)",
    "PM Final Review · Freeze",
  ],
  pmReviewResult: {
    method: "Screen Review",
    date: "2026-07-07",
    finalReviewDate: "2026-07-07",
    decision: "approved-frozen",
    approved: [
      "Purpose",
      "Role",
      "Task Scope",
      "Exit Condition",
      "Layout",
      "Data",
      "Workflow",
      "Automation",
      "Connected Screens",
      "Output",
      "Freeze Criteria",
    ],
    supplementsApplied: [
      "Brand Theme (Primary·Secondary·Font·Report Theme)",
      "Certification 확장 (인증명·인증번호·발급기관·유효기간·상태)",
      "Business Location (본사·공장·창고·주소·연락처)",
    ],
    frozen: true,
    nextStep: "Official Freeze — ⑩ LOT Lifecycle (Final Blueprint)",
  },
  asBuiltGap: [
    "Company Store 분리 (Config/Session → Store) — 구현 단계",
    "Brand Theme (Form Engine) — Blueprint only · 구현 나중",
    "Certification 만료 알림 — Roadmap",
    "다중 Business Location — 구현 단계",
  ],
});

export const LOT_LIFECYCLE_BLUEPRINT = defineBlueprint({
  id: "lotLifecycle",
  label: "LOT Lifecycle",
  order: 10,
  menuId: null,
  supporting: true,
  sidebar: false,
  route: "/traceability/lot/{lotNo}",
  docPath: "docs/blueprints/V2.0/lot-lifecycle.md",
  status: "frozen",
  frozenDate: "2026-07-07",
  reviewStatus: "frozen",
  freezePolicy: "구조 변경 ❌ · 개선 = Review 문서(Update)만",
  isWorkspace: true,
  isFinalBlueprint: true,
  phase1Complete: true,
  entry: "Traceability QR Scan (공식)",
  // 최종 Blueprint — 9개 Workspace를 하나의 LOT 중심 시스템으로 연결
  finalBlueprintPrinciple: {
    official: "LOT Lifecycle = TITAN 전체 Workflow의 완성본 (단일 화면 ❌)",
    connects: [
      "HOME",
      "설비현황(Control Room)",
      "운영관리",
      "생산관리",
      "품질관리",
      "통계관리",
      "기준정보관리",
      "환경설정",
      "회사정보",
    ],
    integratedPrinciples: [
      "LOT 중심 (LOT-centric)",
      "Workflow 중심 (TitanWorkflowEngine)",
      "Workspace 중심 (Workspace First)",
      "SSoT (Master/Company Store)",
      "QR Traceability (1 LOT = 1 Traceability QR)",
    ],
    role: [
      "하나의 LOT 전체 이력 조회",
      "QR Scan 최종 도착 화면",
      "Timeline 기반 Traceability",
      "관련 문서 통합 조회",
      "현재 상태·진행률 확인",
      "경영/품질/생산 공통 LOT 소통 화면",
    ],
  },
  officialFlow: [
    "HOME",
    "설비현황(Control Room)",
    "운영관리",
    "생산관리",
    "품질관리",
    "출고",
    "LOT Lifecycle",
  ],
  purpose:
    "TITAN 전체 Workflow 완성본. Traceability QR Scan 최종 도착 화면. 하나의 LOT 전체 Lifecycle 통합 조회 — 개별 문서 열기 ❌. Sidebar ❌.",
  role: {
    allowed: [
      "LOT Lifecycle 조회 (권한별 필드)",
      "Timeline · Document No. 목록 표시",
      "운영/생산/품질/출고 이력 통합 조회",
      "연결 출력물 PDF 링크 (권한)",
    ],
    forbidden: [
      "업무 수행 (등록·수정) — 조회 전용",
      "개별 문서 Deep Link만 여는 UX",
      "문서마다 다른 Traceability QR",
      "QR payload에 Document No. 저장",
    ],
  },
  taskScope: {
    workspaceRole: "QR Scan / LOT 선택 조회 — LOT 전체 Lifecycle (통합 조회)",
    showOnly: [
      "LOT 기본정보 (관리번호·LOT·제품·고객사·현재공정·현재설비·현재상태·진행률)",
      "Timeline",
      "운영/생산/품질/출고 이력",
      "관련 문서 (입고리스트·작업지시서·생산일보·검사리포트·성적서·거래명세서)",
    ],
    hide: ["다른 LOT", "권한 외 필드"],
  },
  exitCondition: {
    completeWhen: "조회 종료 (업무 수행 ❌)",
    removeFromScreen: "해당 없음",
    nextScreen: "권한별 출력물 PDF 링크",
    engine: "TitanWorkflowEngine (상태·진행률 계산)",
  },
  access: {
    sidebar: false,
    entryPoints: ["Traceability QR Scan", "LOT 선택 → LOT Lifecycle"],
  },
  // 공식 화면 구성
  screenComposition: {
    lotBasics: [
      "관리번호",
      "LOT 번호",
      "제품",
      "고객사",
      "현재공정",
      "현재설비",
      "현재상태",
      "진행률",
    ],
    timeline: "Timeline (Traceability)",
    histories: ["운영 이력", "생산 이력", "품질 이력", "출고 이력"],
    relatedDocuments: [
      "입고리스트",
      "작업지시서",
      "생산일보",
      "검사리포트",
      "성적서",
      "거래명세서",
    ],
    footer: ["QR", "PDF", "Document No."],
    lotKpi: [
      "현재 공정",
      "진행률",
      "총 소요시간",
      "현재 작업자",
      "현재 설비",
      "품질 상태",
    ],
  },
  // PM Final Review 보완 — LOT Health
  lotHealth: {
    official: "LOT 상태를 하나의 상태값으로 표현 — 현재 건강 상태 한눈에",
    values: ["정상", "주의", "지연", "완료"],
  },
  // PM Final Review 보완 — LOT KPI (상단 KPI)
  lotKpi: {
    official: "LOT Lifecycle 상단 KPI",
    items: ["현재 공정", "진행률", "총 소요시간", "현재 작업자", "현재 설비", "품질 상태"],
  },
  // PM Final Review 보완 — Related LOT (Blueprint only)
  relatedLot: {
    official: "같은 작업에서 함께 처리된 LOT 표시",
    types: ["같이 장입한 LOT", "동일 작업 LOT", "동일 고객 LOT"],
    implementation: "Blueprint 정의만 · 구현 나중",
  },
  // Timeline 공식 — Engine 자동 생성 · 수정 ❌
  timelineOfficial: {
    official: "LOT 생명주기 시간순 기록 — Engine 자동 생성 · 수정 ❌",
    stages: ["입고", "생산계획", "장입", "생산", "검사", "성적서", "출고"],
  },
  qrPolicy: {
    official: "Traceability QR 최종 목적지 · 1 LOT = 1 Traceability QR",
    rule: "QR payload에 Document No. 저장 ❌",
  },
  dataPolicy: {
    official: "TitanDataEngine → TitanWorkflowEngine → Timeline Store → LOT Lifecycle",
    rule: "Engine 기반 집계만 · 업무 데이터 직접 수정 ❌",
  },
  layout: [
    "Header · LOT 번호 · QR ID (future)",
    "LOT KPI — 현재공정·진행률·총소요시간·작업자·설비·품질상태",
    "LOT Health — 정상·주의·지연·완료",
    "LOT 기본정보 Grid — 관리번호·LOT·제품·고객사·현재공정·현재설비·현재상태·진행률",
    "Timeline (입고→생산계획→장입→생산→검사→성적서→출고 · Engine 자동)",
    "이력 섹션 — 운영 · 생산 · 품질 · 출고",
    "관련 문서 목록 (입고리스트·작업지시서·생산일보·검사리포트·성적서·거래명세서)",
    "Related LOT (같이 장입·동일 작업·동일 고객 · Roadmap)",
    "출력물 영역 — QR · PDF · Document No. (권한)",
  ],
  data: {
    stores: ["lotStore", "productionStore", "qualityStore", "timelineStore", "equipmentStore"],
    masterRef: "Master Store (제품·고객사·설비) · Company Store (출력물 Header) — 참조만",
    model: "lotTraceabilityModel.js · timelineQuery.js",
    engine: "TitanDataEngine → TitanWorkflowEngine → Timeline Store → LOT Lifecycle",
    dataPolicy: "Engine 기반 집계만 · Timeline 수정 ❌",
    qr: "TITAN_TRACEABILITY_QR_LOT_POLICY · TITAN_QR_LOOKUP_PERMISSIONS",
    qrDesign: "TITAN_QR_ID_POLICY · TITAN_QR_VERSION_POLICY (design-only)",
  },
  workflow: [
    "Traceability QR Scan → LOT Lifecycle 화면 (최종 도착)",
    "관리번호 → 제품 → 공정 → 설비 → 진행률",
    "운영 · 생산일보 · 검사 · 성적서 · 출고 · Timeline 통합",
    "역할별 필드 마스킹 (admin · internal · customer)",
  ],
  automation: {
    user: ["Scan only", "조회"],
    system: [
      "LOT resolve",
      "Lifecycle aggregate (운영/생산/품질/출고)",
      "Document No. collect",
      "Timeline by lotNo",
      "진행률·현재상태 계산 (WorkflowEngine)",
      "권한 필터",
    ],
  },
  connectedScreens: {
    role: "9 Workspace 통합 연결 (LOT 중심)",
    aggregatesFrom: ["운영관리", "생산관리", "품질관리", "설비현황", "출고"],
    masterRef: ["기준정보관리(Master Store)", "회사정보(Company Store)"],
    outputsRef: [
      "입고리스트",
      "작업지시서",
      "생산일보",
      "검사리포트",
      "성적서",
      "거래명세서",
    ],
  },
  outputs: ["조회 화면 (출력 ❌)", "연관 PDF 링크", "동일 LOT Traceability QR on prints"],
  completionCriteria: [
    "9 Workspace 통합 연결",
    "LOT 기본정보 · Timeline · 4 이력 · 관련 문서",
    "LOT Health · LOT KPI · Related LOT (Blueprint)",
    "1 LOT = 1 Traceability QR 준수",
    "Engine 기반 (DataEngine·WorkflowEngine·Timeline)",
    "5대 원칙 종합 (LOT·Workflow·Workspace·SSoT·QR)",
    "PM Final Review · Freeze → Phase 1 완료",
  ],
  pmReviewResult: {
    method: "Final Blueprint Review",
    date: "2026-07-07",
    finalReviewDate: "2026-07-07",
    decision: "approved-frozen",
    approved: [
      "Purpose",
      "Role",
      "Task Scope",
      "Exit Condition",
      "Layout",
      "Data",
      "Workflow",
      "Automation",
      "Connected Screens",
      "Output",
      "Freeze Criteria",
    ],
    supplementsApplied: [
      "LOT Health (정상·주의·지연·완료)",
      "LOT KPI (현재공정·진행률·소요시간·작업자·설비·품질)",
      "Related LOT (같이 장입·동일 작업·동일 고객 · Blueprint only)",
      "Timeline 공식 (Engine 자동 · 수정 ❌)",
      "QR Policy (1 LOT = 1 QR · Document No. ❌)",
    ],
    frozen: true,
    phase1Complete: true,
    nextStep: "Phase 2 — Implementation (구현)",
  },
  asBuiltGap: [
    "LOT Lifecycle 통합 화면 — 구현 단계",
    "LOT Health / LOT KPI — 구현 단계",
    "Related LOT — Blueprint only · 구현 나중",
    "Timeline aggregate (4 이력) — 구현 단계",
    "Traceability QR ID/Version — Roadmap",
    "3-tier 권한 마스킹 — 구현 단계",
  ],
});

/** @type {Record<string, TitanBlueprint>} */
export const TITAN_BLUEPRINTS_V17 = {
  home: HOME_BLUEPRINT,
  equipmentMonitor: EQUIPMENT_MONITOR_BLUEPRINT,
  operationsManagement: OPERATIONS_MANAGEMENT_BLUEPRINT,
  productionManagement: PRODUCTION_MANAGEMENT_BLUEPRINT,
  qualityManagement: QUALITY_MANAGEMENT_BLUEPRINT,
  statistics: STATISTICS_BLUEPRINT,
  masterData: MASTER_DATA_BLUEPRINT,
  environment: ENVIRONMENT_BLUEPRINT,
  companyInfo: COMPANY_INFO_BLUEPRINT,
  lotLifecycle: LOT_LIFECYCLE_BLUEPRINT,
  mobileQrPortal: MOBILE_QR_PORTAL_BLUEPRINT,
  qrMenuShortcut: QR_MENU_SHORTCUT_BLUEPRINT,
  documentManagementV101: DOCUMENT_MANAGEMENT_V101_BLUEPRINT,
};

/** V2.0 alias — 명시적 명칭 */
export const TITAN_BLUEPRINTS_V20 = TITAN_BLUEPRINTS_V17;

/** @param {string} id */
export function getBlueprintV17(id) {
  return TITAN_BLUEPRINTS_V17[id] ?? null;
}

export function listBlueprintsV17() {
  return Object.values(TITAN_BLUEPRINTS_V17);
}
