/** Project TITAN — 공통 출력 Footer (PM Official Print Standard) */
function TitanPrintOfficialFooter({ notes = [] }) {
  const defaultNotes = [
    "※ 작업수량 / 작업일 / LOT No.는 생산부에서 작성합니다.",
    "※ 생산일보 등록 시 작성된 내용을 전산 입력합니다.",
  ];
  const lines = notes.length > 0 ? notes : defaultNotes;

  return (
    <footer className="titan-print-official-footer" aria-label="출력물 안내">
      <div className="titan-print-official-footer__notes">
        {lines.map((line) => (
          <p key={line}>{line}</p>
        ))}
      </div>
      <p className="titan-print-official-footer__brand">
        Generated by Project TITAN
        <br />
        NDK QMS Professional
      </p>
    </footer>
  );
}

export default TitanPrintOfficialFooter;
