import {
  TITAN_PRINT_ENGINE_VERSION,
  TITAN_PRINT_LAYOUT_VERSION,
} from "../../config/titanListPrintStandard";

/** Project TITAN — 공통 출력 Footer (PM Official Print Standard) */
function TitanPrintOfficialFooter({
  notes = [],
  documentCode = "DOC-01",
  printEngineVersion = TITAN_PRINT_ENGINE_VERSION,
  layoutVersion = TITAN_PRINT_LAYOUT_VERSION,
}) {
  const defaultNotes = [
    "※ 작업수량 / 작업일 / LOT No.는 생산부에서 작성합니다.",
    "※ 생산일보 등록 시 작성된 내용을 전산 입력합니다.",
  ];
  const lines = notes.length > 0 ? notes : defaultNotes;

  return (
    <footer className="titan-print-official-footer" aria-label="출력물 안내">
      <div className="titan-print-official-footer__notes">
        {lines.map((line) => (
          <p key={line}>{line}</p>
        ))}
      </div>
      <div className="titan-print-official-footer__brand">
        <p className="titan-print-official-footer__meta">
          Document : {documentCode}
          <br />
          Print Engine : {printEngineVersion}
          <br />
          Layout Version : {layoutVersion}
        </p>
        <p>
          Generated by Project TITAN
          <br />
          NDK PQMS Professional
        </p>
      </div>
    </footer>
  );
}

export default TitanPrintOfficialFooter;
