/** Project TITAN — Standard Detail Popup (UI Freeze) 고정 규격 */
export const TITAN_STANDARD_DETAIL_POPUP_WIDTH = 880;
export const TITAN_STANDARD_DETAIL_POPUP_HEIGHT = 660;
export const TITAN_STANDARD_DETAIL_POPUP_CHROME_HEIGHT = 240;
export const TITAN_STANDARD_DETAIL_POPUP_CONTENT_HEIGHT =
  TITAN_STANDARD_DETAIL_POPUP_HEIGHT - TITAN_STANDARD_DETAIL_POPUP_CHROME_HEIGHT;

export const TITAN_STANDARD_DETAIL_POPUP_LAYOUT = {
  width: TITAN_STANDARD_DETAIL_POPUP_WIDTH,
  height: TITAN_STANDARD_DETAIL_POPUP_HEIGHT,
  chromeHeight: TITAN_STANDARD_DETAIL_POPUP_CHROME_HEIGHT,
  contentHeight: TITAN_STANDARD_DETAIL_POPUP_CONTENT_HEIGHT,
};
