/** Project TITAN V1.4 — 문서관리 Detail Popup (일반 880×660 대비 확대 · PM 승인) */
export const TITAN_DOCUMENT_DETAIL_POPUP_WIDTH = 1120;
export const TITAN_DOCUMENT_DETAIL_POPUP_HEIGHT = 720;

export const TITAN_DOCUMENT_COMPANY_POPUP_WIDTH = 1120;

export const TITAN_DOCUMENT_DETAIL_POPUP_LAYOUT = {
  width: TITAN_DOCUMENT_DETAIL_POPUP_WIDTH,
  height: TITAN_DOCUMENT_DETAIL_POPUP_HEIGHT,
};
