import {
  BarChart3,
  Calculator,
  Database,
  Factory,
  LayoutGrid,
  Monitor,
  Package,
  QrCode,
  Truck,
  Wallet,
} from "lucide-react";
import { OPERATION_ROUTES } from "./operationsRouteRegistry";

/**
 * HOME 업무 바로가기 — V1.5 UI Freeze (2×3 Launcher Grid)
 * @see src/pages/Home/HomeWorkLauncherPanel.jsx
 */
export const HOME_WORK_LAUNCHER_ITEMS = [
  {
    id: "inbound",
    label: "입고관리",
    badge: "입고",
    tone: "blue",
    path: "/inout",
    ctaLabel: "입고등록",
    icon: Package,
    moduleId: "inbound",
    metrics: [
      { key: "todayIncoming", label: "금일 입고", suffix: "건" },
      { key: "inboundWait", label: "입고 대기", suffix: "건" },
    ],
  },
  {
    id: "equipmentStatus",
    label: "설비현황",
    badge: "관제",
    tone: "orange",
    path: OPERATION_ROUTES.equipmentStatus,
    ctaLabel: "설비 가동 현황",
    icon: Monitor,
    moduleId: "qrSystem",
    metrics: [
      { key: "running", label: "운전중", suffix: "대" },
      { key: "ready", label: "장입 준비", suffix: "대" },
      { key: "maintenance", label: "점검중", suffix: "대" },
    ],
  },
  {
    id: "productStatus",
    label: "제품 현황",
    badge: "추적",
    tone: "green",
    path: `${OPERATION_ROUTES.equipmentStatus}?view=product`,
    ctaLabel: "제품 추적",
    icon: LayoutGrid,
    moduleId: null,
    metrics: [
      { key: "inProgress", label: "진행중", suffix: "건" },
      { key: "inspectionWait", label: "검사대기", suffix: "건" },
      { key: "shipWait", label: "출고대기", suffix: "건" },
    ],
  },
  {
    id: "qrCharging",
    label: "설비 가동 현황",
    badge: "관제/작업",
    tone: "purple",
    path: OPERATION_ROUTES.equipmentStatus,
    ctaLabel: "작업 시작",
    icon: Factory,
    moduleId: "qrSystem",
    metrics: [
      { key: "chargeableLots", label: "장입 가능 LOT", suffix: "건" },
      { key: "runningEquipment", label: "운전중 설비", suffix: "대" },
    ],
  },
  {
    id: "outbound",
    label: "출고관리",
    badge: "출고",
    tone: "yellow",
    path: "/inout",
    ctaLabel: "출고등록",
    icon: Truck,
    moduleId: "outbound",
    metrics: [
      { key: "todayShipment", label: "금일 출고", suffix: "건" },
      { key: "shipWait", label: "출고 대기", suffix: "건" },
    ],
  },
  {
    id: "statistics",
    label: "통계관리",
    badge: "통계",
    tone: "cyan",
    path: "/statistics",
    ctaLabel: "통계 조회",
    icon: BarChart3,
    moduleId: "statistics",
    metrics: [
      { key: "heatRunning", label: "열처리 중", suffix: "건" },
      { key: "inspectionWait", label: "검사 대기", suffix: "건" },
    ],
  },
  {
    id: "accountingClerk",
    label: "경리관리",
    badge: "경리",
    tone: "blue",
    path: "/accounting-clerk",
    ctaLabel: "명세서 조회",
    icon: Wallet,
    moduleId: "accountingClerk",
    metrics: [
      { key: "activeFeatures", label: "사용 기능", suffix: "개" },
      { key: "statementViews", label: "명세서 조회", suffix: "건" },
    ],
  },
  {
    id: "accounting",
    label: "회계관리",
    badge: "회계",
    tone: "purple",
    path: "/accounting",
    ctaLabel: "회계 조회",
    icon: Calculator,
    moduleId: "accounting",
    metrics: [
      { key: "referenceViews", label: "조회 화면", suffix: "개" },
      { key: "statementViews", label: "거래 조회", suffix: "건" },
    ],
  },
  {
    id: "qrEngine",
    label: "QR 정보관리",
    badge: "QR",
    tone: "cyan",
    path: "/qr",
    ctaLabel: "QR 스캔",
    icon: QrCode,
    moduleId: "qrSystem",
    metrics: [
      { key: "registry", label: "QR 목록", suffix: "건" },
      { key: "scanRoutes", label: "스캔 경로", suffix: "개" },
    ],
  },
];

export const HOME_WORK_DASHBOARD_GROUPS = [
  {
    id: "operations",
    label: "운영관리",
    badge: "운영",
    tone: "blue",
    path: "/inout",
    icon: Package,
    ctaLabel: "운영관리",
    metrics: [
      { key: "todayIncoming", label: "금일 입고", suffix: "건" },
      { key: "inboundWait", label: "입고현황", suffix: "건" },
      { key: "shipWait", label: "출고대기", suffix: "건" },
    ],
  },
  {
    id: "production",
    label: "생산관리",
    badge: "생산",
    tone: "purple",
    path: "/production",
    icon: Factory,
    ctaLabel: "생산관리",
    metrics: [
      { key: "runningLots", label: "생산현황", suffix: "건" },
      { key: "heatWait", label: "열처리 대기", suffix: "건" },
      { key: "productionDone", label: "생산 완료", suffix: "건" },
    ],
  },
  {
    id: "quality",
    label: "품질관리",
    badge: "품질",
    tone: "green",
    path: "/quality",
    icon: LayoutGrid,
    ctaLabel: "품질관리",
    metrics: [
      { key: "inspectionWait", label: "검사 대기", suffix: "건" },
      { key: "certWait", label: "성적서 대기", suffix: "건" },
      { key: "nonConformance", label: "부적합", suffix: "건" },
    ],
  },
  {
    id: "equipment",
    label: "설비관리",
    badge: "설비",
    tone: "orange",
    path: OPERATION_ROUTES.equipmentStatus,
    icon: Monitor,
    ctaLabel: "설비 가동 현황",
    metrics: [
      { key: "running", label: "운전중", suffix: "대" },
      { key: "maintenance", label: "점검중", suffix: "대" },
      { key: "ready", label: "장입 준비", suffix: "대" },
    ],
  },
  {
    id: "masterData",
    label: "기준정보관리",
    badge: "Master",
    tone: "yellow",
    path: "/settings/hub",
    icon: Database,
    ctaLabel: "Master Dashboard",
    denseMetrics: true,
    metrics: [
      { key: "companies", label: "거래처", suffix: "개" },
      { key: "products", label: "제품", suffix: "개" },
      { key: "materials", label: "재질", suffix: "개" },
      { key: "processes", label: "공정", suffix: "개" },
      { key: "equipment", label: "설비", suffix: "대" },
      { key: "workers", label: "작업자", suffix: "명" },
    ],
  },
  {
    id: "management",
    label: "경영지원",
    badge: "경영",
    tone: "cyan",
    path: "/accounting-clerk",
    icon: Wallet,
    ctaLabel: "경영지원",
    metrics: [
      { key: "statements", label: "거래명세서", suffix: "건" },
      { key: "clerkViews", label: "경리", suffix: "개" },
      { key: "accountingViews", label: "회계", suffix: "개" },
    ],
  },
];