/**
 * Project TITAN V1.1 - Master SSoT Registry (PM 2026-07-11 - Master First Freeze)
 * @see docs/blueprints/V1.1/MASTER_FIRST_FREEZE.md
 */

import { PROCESS_WORKFLOW_TEMPLATES_STORAGE_KEY } from "./processWorkflowTemplates";
import { INSPECTION_TEMPLATE_MASTER_STORAGE_KEY } from "./inspectionTemplateMaster";
import { CERTIFICATE_POLICY_MASTER_STORAGE_KEY } from "./certificatePolicyMaster";
import { TITAN_NUMBERING_STORAGE_KEY } from "./masterDataScreens";

/** @typedef {"complete" | "partial" | "hold" | "deferred"} V11MasterSsotStatus */

export const V11_MASTER_SSOT_REGISTRY = Object.freeze([
  {
    id: "company",
    label: "\uAC70\uB798\uCC98 Master",
    order: 1,
    action: "keep",
    storageKey: "project-titan-master-data-v3.companies",
    configPath: "src/config/companyDetailSections.js",
    sessionPath: "src/utils/masterData.js",
    uiRoute: "/settings/companies",
    uiComponent: "src/pages/Settings/CompanyManagementPage.jsx",
    status: "complete",
    requiredFields: ["id", "code", "name", "abbreviation", "active"],
    knownIssues: [],
    downstreamConsumers: ["InboundManagement", "companyAbbreviation", "createSessionRepositories"],
    notes: "PM 2026-07-11: Keep as-is.",
  },
  {
    id: "product",
    label: "\uC81C\uD488 Master",
    order: 2,
    action: "deferred",
    storageKey: "project-titan-master-data-v3.products",
    configPath: "src/config/productDetailSections.js",
    sessionPath: "src/utils/masterData.js",
    uiRoute: "/settings/products",
    uiComponent: "src/pages/Settings/ProductManagementPage.jsx",
    status: "deferred",
    requiredFields: ["code", "company", "partNo", "inspectionTemplateId", "certificatePolicyId", "processWorkflowTemplateId"],
    knownIssues: ["Full redesign deferred", "Inline process workflow editor remains"],
    downstreamConsumers: ["InboundManagement", "DailyProductionReport", "InspectionLogManagement"],
    notes: "Maintain existing UI. Template/policy dropdowns active.",
  },
  {
    id: "material",
    label: "\uC7AC\uC9C8 Master",
    order: 3,
    action: "simplify",
    storageKey: "project-titan-master-data-v3.materials",
    configPath: "src/config/materialDetailSections.js",
    sessionPath: "src/utils/masterData.js",
    uiRoute: "/settings/materials",
    uiComponent: "src/pages/Settings/MasterEntityManagementPage.jsx",
    status: "complete",
    requiredFields: ["code", "name", "active"],
    knownIssues: ["Detail heat tabs read-only computed"],
    downstreamConsumers: ["MasterDataRegisterModal", "ProductManagementPage", "InventoryStatusPage"],
    notes: "Settings UI: name, code, active only.",
  },
  {
    id: "equipment",
    label: "\uC124\uBE44 Master",
    order: 4,
    action: "simplify",
    storageKey: "project-titan-master-data-v3.equipment",
    configPath: "src/config/equipmentConfig.js",
    sessionPath: "src/utils/masterData.js",
    uiRoute: "/settings/equipment",
    uiComponent: "src/pages/Settings/MasterEntityManagementPage.jsx",
    status: "complete",
    requiredFields: ["name", "equipType", "active"],
    knownIssues: [],
    downstreamConsumers: ["equipmentWorkflowService", "EquipmentStatusPage", "DailyProductionReportRegisterModal"],
    notes: "Settings UI: name, heat-treatment process, active. Code auto from name.",
  },
  {
    id: "worker",
    label: "\uC791\uC5C5\uC790 Master",
    order: 5,
    action: "keep",
    storageKey: "project-titan-master-data-v3.workers",
    configPath: "src/config/workerDetailSections.js",
    sessionPath: "src/utils/masterData.js",
    uiRoute: "/settings/workers",
    uiComponent: "src/pages/Settings/MasterEntityManagementPage.jsx",
    status: "complete",
    requiredFields: ["code", "name", "department", "role", "active"],
    knownIssues: ["Future: production report / inspection history assignee linkage"],
    downstreamConsumers: ["DailyProductionReportRegisterModal", "InspectionLogEntryModal"],
    notes: "PM 2026-07-11: Keep as-is.",
  },
  {
    id: "processType",
    label: "\uACF5\uC815\uC720\uD615 Master",
    order: 6,
    action: "stabilize",
    storageKey: PROCESS_WORKFLOW_TEMPLATES_STORAGE_KEY,
    configPath: "src/config/processWorkflowTemplates.js",
    sessionPath: "src/utils/processWorkflowTemplateSession.js",
    uiRoute: "/environment/process-templates",
    uiComponent: "src/pages/Environment/EnvironmentSections.jsx",
    status: "partial",
    requiredFields: ["id", "label", "steps", "builtIn"],
    knownIssues: ["Future PVD / plating / oxidation hooks not implemented"],
    downstreamConsumers: ["MasterDataRegisterModal", "productProcessWorkflow", "InboundManagement"],
    notes: "Environment CRUD active.",
  },
  {
    id: "inspectionTemplate",
    label: "\uAC80\uC0AC Template Master",
    order: 7,
    action: "stabilize",
    storageKey: INSPECTION_TEMPLATE_MASTER_STORAGE_KEY,
    configPath: "src/config/inspectionTemplateMaster.js",
    sessionPath: "src/utils/inspectionTemplateSession.js",
    uiRoute: "/environment/inspection-templates",
    uiComponent: "src/pages/Environment/V11MasterAdminSections.jsx",
    status: "partial",
    requiredFields: ["id", "label", "specification", "builtIn"],
    knownIssues: ["No delete guard when product references template"],
    downstreamConsumers: ["MasterDataRegisterModal", "productMasterInspectionSpec"],
    notes: "Environment CRUD active. Product selects template only.",
  },
  {
    id: "certificatePolicy",
    label: "\uC131\uC801\uC11C \uC815\uCC45 Master",
    order: 8,
    action: "stabilize",
    storageKey: CERTIFICATE_POLICY_MASTER_STORAGE_KEY,
    configPath: "src/config/certificatePolicyMaster.js",
    sessionPath: "src/utils/certificatePolicySession.js",
    uiRoute: "/environment/certificate-policies",
    uiComponent: "src/pages/Environment/V11MasterAdminSections.jsx",
    status: "partial",
    requiredFields: ["id", "label", "issuePolicy", "builtIn"],
    knownIssues: ["Inbound override bypasses product default policy"],
    downstreamConsumers: ["MasterDataRegisterModal", "certificateIssuePolicy", "CertificateManagement"],
    notes: "Environment CRUD active. Inbound override preserved.",
  },
  {
    id: "numbering",
    label: "\uBC88\uD638\uCCB4\uACC4 Master",
    order: 9,
    action: "stabilize",
    storageKey: TITAN_NUMBERING_STORAGE_KEY,
    configPath: "src/config/masterDataScreens.js",
    sessionPath: "src/utils/masterData.js",
    uiRoute: "/environment/numbering",
    uiComponent: "src/pages/Environment/EnvironmentSections.jsx",
    status: "partial",
    requiredFields: ["prefixes"],
    knownIssues: ["Management number / LOT rules need end-to-end QA"],
    downstreamConsumers: ["generateTitanDocumentNumberFromSettings", "chargeLotNumber"],
    notes: "Environment numbering CRUD at /environment/numbering.",
  },
  {
    id: "defectCode",
    label: "\uBD88\uB7C9\uCF54\uB4DC Master",
    order: 10,
    action: "hold",
    storageKey: "project-titan-master-data-v3.customCodes",
    configPath: "src/config/masterDataScreens.js",
    sessionPath: "src/utils/masterData.js",
    uiRoute: "/settings/hold/defect-codes",
    uiComponent: "src/pages/Settings/MasterHoldPlaceholderPage.jsx",
    status: "hold",
    requiredFields: [],
    knownIssues: ["UI placeholder only - defectHistorySession retained"],
    downstreamConsumers: ["DefectHistoryManagement"],
    notes: "Do NOT delete code.",
  },
  {
    id: "customCode",
    label: "\uC0AC\uC6A9\uC790\uC815\uC758\uCF54\uB4DC Master",
    order: 10,
    action: "hold",
    storageKey: "project-titan-master-data-v3.customCodes",
    configPath: "src/config/masterDataScreens.js",
    sessionPath: "src/utils/masterData.js",
    uiRoute: "/settings/hold/custom-codes",
    uiComponent: "src/pages/Settings/MasterHoldPlaceholderPage.jsx",
    status: "hold",
    requiredFields: [],
    knownIssues: ["MasterDataManagement(customCodes) code retained - route gated"],
    downstreamConsumers: ["masterData customCodes group aliases"],
    notes: "Do NOT delete code.",
  },
]);

export const V11_MASTER_SSOT_SUMMARY = Object.freeze({
  sprintDate: "2026-07-11",
  principle: "Master First -> Automation First -> Exception Allowed",
  workflowReconnect: "AFTER master sprint 1-9 complete",
  totalMasters: V11_MASTER_SSOT_REGISTRY.length,
  complete: V11_MASTER_SSOT_REGISTRY.filter((m) => m.status === "complete").length,
  partial: V11_MASTER_SSOT_REGISTRY.filter((m) => m.status === "partial").length,
  hold: V11_MASTER_SSOT_REGISTRY.filter((m) => m.status === "hold").length,
  deferred: V11_MASTER_SSOT_REGISTRY.filter((m) => m.status === "deferred").length,
});

export function getV11MasterById(masterId) {
  return V11_MASTER_SSOT_REGISTRY.find((row) => row.id === masterId) ?? null;
}

export function getV11MasterCompletionTable() {
  return V11_MASTER_SSOT_REGISTRY.map((row) => ({
    id: row.id,
    label: row.label,
    order: row.order,
    action: row.action,
    status: row.status,
    uiRoute: row.uiRoute,
    storageKey: row.storageKey,
  }));
}

export default V11_MASTER_SSOT_REGISTRY;
