import path from "node:path";
import { pathToFileURL } from "node:url";
const root = path.resolve(path.dirname(new URL(import.meta.url).pathname.replace(/^\/([A-Z]:)/, "$1")), "..");
const memory = new Map();
globalThis.sessionStorage = { getItem:(k)=>memory.get(k)??null, setItem:(k,v)=>memory.set(k,String(v)), removeItem:(k)=>memory.delete(k), clear:()=>memory.clear(), get length(){return memory.size}, key:(i)=>[...memory.keys()][i]??null };
globalThis.localStorage = { getItem:()=>null, setItem:()=>{}, removeItem:()=>{}, clear:()=>{}, get length(){return 0}, key:()=>null };
globalThis.window = { dispatchEvent:()=>{}, addEventListener:()=>{}, removeEventListener:()=>{} };
const { resetTitanDataEngineInstance, getTitanDataEngine } = await import(pathToFileURL(path.join(root,"src/foundation/data/index.js")).href);
const { replaceSessionProductionRecords, addSessionProductionRecord, getSessionProductionRecords } = await import(pathToFileURL(path.join(root,"src/utils/productionRecords.js")).href);
const { WORKFLOW_STATUS, applyMoveToProductionWaiting, isProductionWaitingStageRecord, getWorkflowStatus } = await import(pathToFileURL(path.join(root,"src/utils/titanWorkflowStatus.js")).href);
const { getChargeableLots, getEquipmentById } = await import(pathToFileURL(path.join(root,"src/utils/equipmentWorkflowService.js")).href);
const { EQUIPMENT_RAW_LIST } = await import(pathToFileURL(path.join(root,"src/config/equipmentConfig.js")).href);
const { syncMasterCategoryToStore } = await import(pathToFileURL(path.join(root,"src/foundation/data/master/masterDataSync.js")).href);
resetTitanDataEngineInstance(); getTitanDataEngine();
syncMasterCategoryToStore("equipment", EQUIPMENT_RAW_LIST.filter((r)=>!r.maintenance).map((r)=>({id:r.id,code:r.code,name:r.name,process:r.process,active:true})));
replaceSessionProductionRecords([]);
addSessionProductionRecord({ id:"T1", mesManagementNo:"T1", company:"C", partName:"P", partNo:"P1", material:"SCM440", qty:3, heatTreatment:"\uC774\uC628\uC9C8\uD654", processDetail:"\uC774\uC628\uC9C8\uD654", incomingRegistered:true, registered:false, workflowStatus:WORKFLOW_STATUS.WORK_WAIT, lotNo:"" });
applyMoveToProductionWaiting(["T1"]);
const r = getSessionProductionRecords().find((x)=>x.id==="T1");
const eq = getEquipmentById("ION-01");
const lots = getChargeableLots("ION-01");
console.log("wf", getWorkflowStatus(r), "isPW", isProductionWaitingStageRecord(r));
console.log("eq", eq?.id, eq?.process, eq?.status, "lots", lots.length);