import path from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const memory = new Map();
globalThis.sessionStorage = { getItem:(k)=>memory.get(k)??null, setItem:(k,v)=>memory.set(k,String(v)), removeItem:(k)=>memory.delete(k), clear:()=>memory.clear(), get length(){return memory.size}, key:(i)=>[...memory.keys()][i]??null };
globalThis.localStorage = { getItem:()=>null, setItem:()=>{}, removeItem:()=>{}, clear:()=>{}, get length(){return 0}, key:()=>null };
globalThis.window = { dispatchEvent:()=>{}, addEventListener:()=>{}, removeEventListener:()=>{} };
const href = (p) => pathToFileURL(path.join(root, p)).href;
const { resetTitanDataEngineInstance, getTitanDataEngine } = await import(href("src/foundation/data/index.js"));
const { replaceSessionProductionRecords, addSessionProductionRecord, getSessionProductionRecords } = await import(href("src/utils/productionRecords.js"));
const { WORKFLOW_STATUS, applyMoveToProductionWaiting, isProductionWaitingStageRecord } = await import(href("src/utils/titanWorkflowStatus.js"));
const { getChargeableLots, ensureLotBeforeCharging, getProductionWaitingRecordsForEquipment } = await import(href("src/utils/equipmentWorkflowService.js"));
const { executeStartCharging } = await import(href("src/utils/titanWorkflowIntegration.js"));
const { buildRc1EquipmentMasterSeedRows } = await import(href("src/data/rc1EquipmentMasterSeed.js"));
const { syncMasterCategoryToStore } = await import(href("src/foundation/data/master/masterDataSync.js"));
const ION = "\uC774\uC628\uC9C8\uD654";
const ID = "RC1-EQ-P018-CROSS-001";
resetTitanDataEngineInstance(); getTitanDataEngine();
syncMasterCategoryToStore("equipment", buildRc1EquipmentMasterSeedRows());
replaceSessionProductionRecords([]);
addSessionProductionRecord({ id:ID, mesManagementNo:ID, company:"RC1", partName:"P018", partNo:"P018-001", material:"SCM440", qty:100, inboundQty:100, incomingRegistered:true, registered:false, workflowStatus:WORKFLOW_STATUS.WORK_WAIT, lotNo:"", heatTreatment:ION, processDetail:ION });
applyMoveToProductionWaiting([ID]);
const row3 = getChargeableLots("3S-1").find(r=>r.sourceRecordId===ID);
const ens = ensureLotBeforeCharging("3S-1", row3);
executeStartCharging({ equipmentId:"3S-1", lotNo:ens.lotNo, chargeQty:30, chargeQtyMeta:{ok:true,chargeQty:30,inboundQty:100,remainingQty:70,isPartial:true}, chargeableRow:{...ens.chargeableRow,chargeQty:30,inboundQty:100,remainingChargeQty:70,isPartialCharge:true}, operator:"op" });
const rec = getSessionProductionRecords().find(r=>r.id===ID);
console.log("session", {remain:rec.remainingChargeQty, wf:rec.workflowStatus, reg:rec.registered, lot:rec.lotNo, waiting:isProductionWaitingStageRecord(rec)});
console.log("waiting pool 3S-2", getProductionWaitingRecordsForEquipment("\uC774\uC628\uC9C8\uD654","ION").map(r=>r.id));
console.log("lots 3S-2", getChargeableLots("3S-2").length, getChargeableLots("3S-2").map(r=>r.qty));
console.log("lots 10S-01", getChargeableLots("10S-01").length, getChargeableLots("10S-01").map(r=>r.qty));
