import path from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(__dirname, "..");
const memory = new Map();
globalThis.sessionStorage = { getItem:(k)=>memory.get(k)??null, setItem:(k,v)=>memory.set(k,String(v)), removeItem:(k)=>memory.delete(k), clear:()=>memory.clear(), get length(){return memory.size}, key:(i)=>[...memory.keys()][i]??null };
globalThis.localStorage = { getItem:()=>null, setItem:()=>{}, removeItem:()=>{}, clear:()=>{}, get length(){return 0}, key:()=>null };
globalThis.window = { dispatchEvent:()=>{}, addEventListener:()=>{}, removeEventListener:()=>{} };
const { resetTitanDataEngineInstance, getTitanDataEngine } = await import(pathToFileURL(path.join(root,"src/foundation/data/index.js")).href);
const { replaceSessionProductionRecords, addSessionProductionRecord } = await import(pathToFileURL(path.join(root,"src/utils/productionRecords.js")).href);
const { stageMasterAdd } = await import(pathToFileURL(path.join(root,"src/utils/masterData.js")).href);
const { resolveCertificateIssuePolicy, skipsCertificateWaitByDefault } = await import(pathToFileURL(path.join(root,"src/utils/certificateIssuePolicy.js")).href);
const { resolveRecordCurrentProcess, CURRENT_PROCESS_KEYS } = await import(pathToFileURL(path.join(root,"src/utils/workflowProcessStatus.js")).href);
const { addInspectionLog, buildInspectionLogFromRecord } = await import(pathToFileURL(path.join(root,"src/utils/inspectionLogSession.js")).href);
const { CERTIFICATE_ISSUE_POLICY } = await import(pathToFileURL(path.join(root,"src/utils/certificateIssuePolicy.js")).href);
const COMPANY = "GP0\uAC70\uB798\uCC98";
resetTitanDataEngineInstance(); getTitanDataEngine();
replaceSessionProductionRecords([]);
stageMasterAdd("companies", { name: COMPANY, code: "GP0TC" });
const pr = stageMasterAdd("products", { company: COMPANY, partNo: "GP0-N-001", name: "GP0\uB0B4\uC6A9\uD488", material: "SCM440", processCategory: "heatTreatment", processDetail: "\uC774\uC628\uC9C8\uD654", process: "\uC774\uC628\uC9C8\uD654", specification: { certificatePolicy: { issuePolicy: CERTIFICATE_ISSUE_POLICY.NEVER_ISSUE } } });
console.log("product spec", JSON.stringify(pr.row?.specification?.certificatePolicy));
addSessionProductionRecord({ id:"GP0-NEVER-001", mesManagementNo:"GP0-NEVER-001", company: COMPANY, partName:"GP0\uB0B4\uC6A9\uD488", partNo:"GP0-N-001", material:"SCM440", qty:3, heatTreatment:"\uC774\uC628\uC9C8\uD654", incomingRegistered:true, registered:true, lotNo:"LOT-1", workflowStatus:"\uAC80\uC0AC\uC644\uB8CC" });
const record = (await import(pathToFileURL(path.join(root,"src/utils/productionRecords.js")).href)).getSessionProductionRecords().find(r=>r.id==="GP0-NEVER-001");
addInspectionLog(buildInspectionLogFromRecord(record, { judgment: "\uD569\uACA9" }));
const after = (await import(pathToFileURL(path.join(root,"src/utils/productionRecords.js")).href)).getSessionProductionRecords().find(r=>r.id==="GP0-NEVER-001");
console.log("policy", resolveCertificateIssuePolicy(after));
console.log("skips", skipsCertificateWaitByDefault(after));
console.log("process", resolveRecordCurrentProcess(after).key);