import path from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(__dirname, "..");
const memory = new Map();
globalThis.sessionStorage = { getItem:(k)=>memory.get(k)??null, setItem:(k,v)=>memory.set(k,String(v)), removeItem:(k)=>memory.delete(k), clear:()=>memory.clear(), get length(){return memory.size}, key:(i)=>[...memory.keys()][i]??null };
globalThis.localStorage = { getItem:()=>null, setItem:()=>{}, removeItem:()=>{}, clear:()=>{}, get length(){return 0}, key:()=>null };
globalThis.window = { dispatchEvent:()=>{}, addEventListener:()=>{}, removeEventListener:()=>{} };
const { resetTitanDataEngineInstance, getTitanDataEngine } = await import(pathToFileURL(path.join(root,"src/foundation/data/index.js")).href);
const { replaceSessionProductionRecords, addSessionProductionRecord, getSessionProductionRecords } = await import(pathToFileURL(path.join(root,"src/utils/productionRecords.js")).href);
const { WORKFLOW_STATUS, applyMoveToProductionWaiting } = await import(pathToFileURL(path.join(root,"src/utils/titanWorkflowStatus.js")).href);
const { getChargeableLots, ensureLotBeforeCharging } = await import(pathToFileURL(path.join(root,"src/utils/equipmentWorkflowService.js")).href);
const { executeStartCharging, executeFinishCharging } = await import(pathToFileURL(path.join(root,"src/utils/titanWorkflowIntegration.js")).href);
const { resolveRecordCurrentProcess, CURRENT_PROCESS_KEYS } = await import(pathToFileURL(path.join(root,"src/utils/workflowProcessStatus.js")).href);
const { addInspectionLog, buildInspectionLogFromRecord } = await import(pathToFileURL(path.join(root,"src/utils/inspectionLogSession.js")).href);
const { resolveCertificateIssuePolicy, skipsCertificateWaitByDefault, CERTIFICATE_ISSUE_POLICY } = await import(pathToFileURL(path.join(root,"src/utils/certificateIssuePolicy.js")).href);
const { getStockQty } = await import(pathToFileURL(path.join(root,"src/utils/inventory.js")).href);
const { findProductByCompanyAndPartNo } = await import(pathToFileURL(path.join(root,"src/utils/masterData.js")).href);
const { stageMasterAdd } = await import(pathToFileURL(path.join(root,"src/utils/masterData.js")).href);
const { EQUIPMENT_RAW_LIST } = await import(pathToFileURL(path.join(root,"src/config/equipmentConfig.js")).href);
const { syncMasterCategoryToStore } = await import(pathToFileURL(path.join(root,"src/foundation/data/master/masterDataSync.js")).href);
const COMPANY = "GP0\uAC70\uB798\uCC98";
const ION = "\uC774\uC628\uC9C8\uD654";
resetTitanDataEngineInstance(); getTitanDataEngine();
syncMasterCategoryToStore("equipment", EQUIPMENT_RAW_LIST.filter((r)=>!r.maintenance).map((r)=>({id:r.id,code:r.code,name:r.name,process:r.process,active:true})));
replaceSessionProductionRecords([]);
stageMasterAdd("companies", { name: COMPANY, code: "GP0TC" });
stageMasterAdd("products", { company: COMPANY, partNo: "GP0-N-001", name: "GP0\uB0B4\uC6A9\uD488", material: "SCM440", processCategory: "heatTreatment", processDetail: ION, process: ION, specification: { certificatePolicy: { issuePolicy: CERTIFICATE_ISSUE_POLICY.NEVER_ISSUE } } });
addSessionProductionRecord({ id:"GP0-NEVER-001", mesManagementNo:"GP0-NEVER-001", company: COMPANY, partName:"GP0\uB0B4\uC6A9\uD488", partNo:"GP0-N-001", material:"SCM440", qty:3, heatTreatment:ION, processDetail:ION, incomingRegistered:true, registered:false, workflowStatus:"", lotNo:"" });
applyMoveToProductionWaiting(["GP0-NEVER-001"]);
const waitingRow = getChargeableLots("ION-01").find((row)=>String(row.sourceRecordId).trim()==="GP0-NEVER-001");
const ensured = ensureLotBeforeCharging("ION-01", waitingRow);
executeStartCharging({ equipmentId:"ION-01", lotNo: ensured.lotNo, chargeableRow: waitingRow, operator:"\uC0DD\uC0B0\uBD80" });
executeFinishCharging({ equipmentId:"ION-01", lotNo: ensured.lotNo, chargeableRow: waitingRow, operator:"\uC0DD\uC0B0\uBD80" });
let record = getSessionProductionRecords().find((r)=>r.id==="GP0-NEVER-001");
console.log("before inspection process", resolveRecordCurrentProcess(record).key);
console.log("product found", Boolean(findProductByCompanyAndPartNo(COMPANY, "GP0-N-001")));
addInspectionLog(buildInspectionLogFromRecord(record, { judgment: "\uD569\uACA9", assignee: "\uC0DD\uC0B0\uBD80" }));
record = getSessionProductionRecords().find((r)=>r.id==="GP0-NEVER-001");
console.log("policy", resolveCertificateIssuePolicy(record));
console.log("skips", skipsCertificateWaitByDefault(record));
console.log("stock", getStockQty(record));
console.log("after inspection process", resolveRecordCurrentProcess(record).key, "expected", CURRENT_PROCESS_KEYS.SHIP_WAIT);