const fs = require("fs");
const path = require("path");
const file = path.join(__dirname, "..", "src", "config", "masterDataScreens.js");
let s = fs.readFileSync(file, "utf8");
const oldText = `    formFields: [\r\n      { key: "code", label: "관리번호", required: true, placeholder: "예: SE_20260702_001" },\r\n      { key: "company", label: "업체명", required: true, optionsKey: "companies", placeholder: "업체 선택" },\r\n      { key: "partNo", label: "품번", required: true, placeholder: "예: WS-2210-F" },\r\n      { key: "name", label: "품명", required: true, placeholder: "예: Pinion Gear" },\r\n      { key: "spec", label: "규격", placeholder: "규격" },\r\n      { key: "material", label: "재질", optionsKey: "materials", placeholder: "재질 선택" },\r\n      { key: "unitPrice", label: "기본단가", placeholder: "예: 1500" },\r\n      { key: "drawingNo", label: "도번", placeholder: "예: 204B1144P0001" },\r\n      { key: "process", label: "기본 공정", optionsKey: "heatTreatment", placeholder: "공정 선택" },\r\n      { key: "unit", label: "기본 단위", optionsKey: "units", placeholder: "단위 선택" },`;
const newText = `    formFields: [\r\n      { key: "company", label: "업체명", required: true, type: "companyAutocomplete", placeholder: "거래처 검색 · 선택" },\r\n      { key: "code", label: "관리번호", type: "autoCode", placeholder: "업체 선택 시 자동 생성 (예: DS-P-0001)" },\r\n      { key: "partNo", label: "품번", required: true, placeholder: "예: WS-2210-F" },\r\n      { key: "name", label: "품명", required: true, placeholder: "예: Pinion Gear" },\r\n      { key: "spec", label: "규격", placeholder: "규격" },\r\n      { key: "material", label: "재질", optionsKey: "materials", placeholder: "재질 선택" },\r\n      { key: "unitPrice", label: "기본단가", placeholder: "예: 1500" },\r\n      { key: "drawingNo", label: "도번", placeholder: "예: 204B1144P0001" },\r\n      { key: "processCategory", label: "공정", type: "processCategory", required: true, placeholder: "공정 분류 선택" },\r\n      { key: "processDetail", label: "세부공정", type: "processDetail", placeholder: "세부공정 선택" },\r\n      { key: "unit", label: "기본 단위", optionsKey: "units", placeholder: "단위 선택" },`;
if (!s.includes(oldText)) throw new Error("miss formFields");
fs.writeFileSync(file, s.replace(oldText, newText), "utf8");
console.log("masterDataScreens ok");
