import { pathToFileURL } from "node:url";
import path from "node:path";
import { fileURLToPath } from "node:url";
const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(__dirname, "..");
const menuPath = pathToFileURL(path.join(root, "src/config/menuStructure.js")).href;
const certPath = pathToFileURL(path.join(root, "src/utils/certificateStatus.js")).href;
const qPath = pathToFileURL(path.join(root, "src/utils/qualityWorkspaceData.js")).href;
const { getSectionByPathname, getSectionById } = await import(menuPath);
const section = getSectionByPathname("/quality/certificate/status");
console.log("section", section?.id, section?.pathPrefix);
console.log("hub", getSectionById("qualityManagement")?.id);
const memory = new Map();
globalThis.sessionStorage = { getItem:(k)=>memory.get(k)??null,setItem:(k,v)=>memory.set(k,String(v)),removeItem:(k)=>memory.delete(k),clear:()=>memory.clear(),get length(){return memory.size},key:(i)=>[...memory.keys()][i]??null};
globalThis.localStorage = { getItem:()=>null,setItem:()=>{},removeItem:()=>{},clear:()=>{},get length(){return 0},key:()=>null};
const { resetTitanDataEngineInstance, getTitanDataEngine } = await import(pathToFileURL(path.join(root,"src/foundation/data/index.js")).href);
resetTitanDataEngineInstance();
getTitanDataEngine();
const { getCertificateHistoryListRows } = await import(certPath);
const { getCertificateHistoryScreenData } = await import(qPath);
const rows = getCertificateHistoryListRows();
const screen = getCertificateHistoryScreenData();
console.log("history rows", rows.length, "screen", screen.baseRecords.length);
